### ISSUE TITLE
Side effects

### ISSUE THREAD

**Issue by hewtungyuen** [nus-cs2030/2021-s2#102]
Towards the end of lecture 10, prof mentioned something regarding side effects. To my understanding, it means that we should not have any user input in the middle of our method chains, but I am not sure if I am correct. Could somebody explain this concept to me? Thanks!

**Comment by Qingyi1115** [comment]
In my understanding, when prof mentions "side effect", I think he didn't mean "bad" side effect. It is just some side code that will run while the main code is running.
