### ISSUE TITLE
Static variables in Project?

### ISSUE THREAD

**Issue by DanielSjtea** [nus-cs2030/2021-s2#114]
# Summary
Cannot use `static` variables unless declared `private final`

## Description 
I was under the impression that we would use `static` mutable variables to keep track of aggregated data for the class. This was pointed out in Lecture 6 whereby the static keyword was first introduced. I am unsure then how we can go about doing this if we are seemingly restricted to declaring all variables as `private final` for the project?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/48090659/112762822-6e68e780-9034-11eb-8124-6206647108ec.png)

**Comment by Onelayer** [comment]
Instead of using static variables to keep track of aggregated data, you can use arrays or ArrayList instead. While ArrayList also needs to be declared private final and the reference will not change, you can change the contents stored in the arraylist. As such, its mutable while keeping to private final requirement.

**Comment by DanielSjtea** [comment]
> Instead of using static variables to keep track of aggregated data, you can use arrays or ArrayList instead. While ArrayList also needs to be declared private final and the reference will not change, you can change the contents stored in the arraylist. As such, its mutable while keeping to private final requirement.

Yeah this is my current workaround, but it just seems like a very weird (and not industrially viable) way to just circumvent the issue.

**Comment by danieltwh** [comment]
Hi DanielSjtea, I am assuming you want to use the static variable to keep track of the wait time and number of customers served. You could also consider creating a new state for the server with the updated total wait time and number of customers served by returning new Server(...) in the methods that handles the arrival of customers. This way, your variables are private final and you can still update them after serving a customer or making them wait. 

Might need to use a Pair class to return both the new server state and the events that occurred while serving the customer (ie Pair<Server, Event[]>). May be a bit more complex than the ArrayList method but it is an alternative to make your Server immutable.

**Comment by dingyuchen** [comment]
I believe the motivation behind enforcing `private final` is to keep all classes immutable. In this case, keeping track of aggregated data with a static variable is no longer possible; static becomes only used for constants.

Alternative work-arounds would be to abstract the aggregation into your runner class, such as Main or another (immutable) container class, that creates a new object upon every update.
