### ISSUE TITLE
Time limit exceeded with (Greatest Common Divisor) method

### ISSUE THREAD

**Issue by KingRyo13** [nus-cs2030/2021-s2#115]
## Description:

As far as I can tell this method returns the correct value for GCD, why am I getting weird time limit exceeded errors in CodeCrunch? Is the method somehow not efficient enough? How can I modify it to pass all the test cases? I have 9/20 test cases passed.

## Code Snippets

![image](https://user-images.githubusercontent.com/77270665/112770325-d16c7580-9058-11eb-8108-74a896f5b9dc.png)

## Screenshots

![image](https://user-images.githubusercontent.com/77270665/112770337-eb0dbd00-9058-11eb-8651-559afc6efd73.png)

**Comment by Onelayer** [comment]
The question stated that you should solve the question using the Euclidean algorithm. https://en.wikipedia.org/wiki/Euclidean_algorithm

**Comment by Xeph-o** [comment]
Try using a pair class instead with the iterate method, and updating the pair with the new variables. Then filter out the pair you need, and use map to obtain the specific value you want

**Comment by cocoy02** [comment]
It takes too long to process. You can try Euclidean Algorithm as mentioned in the question. Here is an example: https://www.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/the-euclidean-algorithm

**Comment by wallytgy** [comment]
This method takes O(n) time, which is okay for small values, but for larger values, the time limit will be exceeded. You need to use the euclidean algorithm and the iterate functions for streams. You also might wanna use a Pair class to store the integers.

**Comment by KevinTan1203** [comment]
Avoid using that method. I would recommend you create a helper class that performs the euclidean algo, so all you need to do is to call the map(), filter() and get() methods in your java stream operations

**Comment by KingRyo13** [comment]
Thanks for all the help, I have updated my code to implement Pair class usage and the algo but have run into some errors:

![image](https://user-images.githubusercontent.com/77270665/112824816-94869a00-90bd-11eb-957c-20ee93084280.png)

![image](https://user-images.githubusercontent.com/77270665/112824861-a49e7980-90bd-11eb-955d-e3a0efe5f76e.png)

First off, my import statement doesn't work when the Pair class in the api is clearly under that. 

Otherwise, is this how it would be done? Pardon me but streams are confusing for me.

Thanks!

**Comment by shankjw** [comment]
For me, I created my own Pair class instead of importing it. I think the Pair class that you are importing is no longer part of JDK when I googled it (https://stackoverflow.com/questions/55170520/package-javafx-util-does-not-exist).

**Comment by KingRyo13** [comment]
> For me, I created my own Pair class instead of importing it. I think the Pair class that you are importing is no longer part of JDK when I googled it (https://stackoverflow.com/questions/55170520/package-javafx-util-does-not-exist).

I did that and solved it, thanks!
