### ISSUE TITLE
Project level 4

### ISSUE THREAD

**Issue by OuaisBien** [nus-cs2030/2021-s2#120]
# Summary
When and how to determine how long the break is for a `Server`?

## Description 
I know the `restLength` is provided and it should be assigned to `Server` with respect to the order of `Done` event chronologically. So I assigned the `restLength` to a `Server` when a `Customer` starts to be served. I handle this at `Serve` event because I had to make sure the start time of subsequent `Wait` or `Serve` event in the queue is correct. However, this does not work when a `Customer` arrives earlier but somehow leaves later than another `Customer`(dammit). Should I attempt to update `restLength` of the difficult `Customer` that takes extra time to serve or is this even the way to go? Any suggestion?

**Comment by kaiwenyay** [comment]
What I did was basically whenever a Serve event is executed I check if that event is possible, given the current state of the servers. If its not, I generate a new Serve event and kinda 'reschedule' the event.

**Comment by coding4soup** [comment]
Hello OuaisBien,

Do you have another event Rest? If you don't, I think it's a good idea to create a Rest event.

The order of events would be
Arrive -> Leave
or
Arrive -> (Wait) -> Serve -> Done -> Rest

So, you would handle the rest times in Rest class instead.
This way, you can let a Server rest for a time of 0 or any value provided in the input.

Anyways, to answer your question, getting rest time chronologically can be done by putting all of the rest times into an ArrayList,
then grabbing the head of that array list each time, then removing the first element of index 0. This ensures you get the first element of the list each time. That way, you won't have to worry about customers leaving earlier.

Hope this helps!

**Comment by brigittesantoso** [comment]
Hi OuaisBien, 

I feel that you shouldn't assign the restLength to a Server when a Customer starts to be served as Level4 stated that "Note that we do not pre-determine which rest time is accorded to which server at the beginning; it can only be decided during the actual simulation. That is to say, whenever a server rests, it will then know how much time it has to rest." 

I would recommend you to create an additional RestEvent class like what coding4soup has mentioned which your DoneEvent leads to. Whenever RestEvent occurs, it will then pop out the first restTime from the restTime ArrayList which is added to the specific server's nextAvailableTime. This way, you are not tagging the restTime to a specific customer but instead only takes in a restTime when RestEvent occurs. 

Hope this solves your problem!

**Comment by gableejh** [comment]
Yup you shouldn't assign a rest length to the customer upon serving but instead it should be upon a done event, since there could be a possibility where customer A is served by server 1 first follow by customer B is served by server 2 but customer B has an earlier done event due to a shorter service time
