### ISSUE TITLE
how to chain ifPresentOrElse / Or to properly use it 

### ISSUE THREAD

**Issue by AdelineWongg** [nus-cs2030/2021-s2#125]
I did something like this
roster.get(studentName).ifPresentOrElse(x ->x.get(moduleName), roster.put(new Student(studentName).put(new Module(moduleName).put(new Assessment(assessmentName, grade)))));
then I got an error which says that roster cannot be converted to a Runnable. I don't understand why

**Comment by g4ryy** [comment]
Hi, the reason why you got this error is because your second argument of the ifPresentOrElse method is not a lambda expression. The ifPresentOrElse method takes in a Consumer as its first argument, followed by a Runnable as its second argument.

**Comment by KingRyo13** [comment]
`ifPresentOrElse(Consumer c, Runnable r)`

The method Consumer implements takes in a variable and returns nothing, hence `x -> x.get(....`
The method Runnable implements takes in nothing and returns nothing, hence you write it like this `() -> roster,put(...`

**Comment by AdelineWongg** [comment]
OH okay thanks g4ryy and KingRyo13
