### ISSUE TITLE
Any Ideas to use stream for level 3?

### ISSUE THREAD

**Issue by AdelineWongg** [nus-cs2030/2021-s2#129]
Hello, I am unsure of how I can make use of streams to do level 3. But for now, I think the idea is iterating through the array and have a variable to keep track of what is the previous number and whether it is accounted for. I think this is possible to solve it with the help of stack but I am not so sure about using streams. Can anyone give me a hint?

**Comment by azelaze** [comment]
Use a stream that contains all indices of the array, that way you can access adjacent array elements just by modifying said index

**Comment by AdelineWongg** [comment]
Hi   @azelaze , did you implement something like a stack to keep track of what is the previous integer and it is part of a new duplicate chain?

**Comment by azelaze** [comment]
umm I used this (no stack I believe)
if element equals to next item BUT not equals to next-next item
			found a sequence of repeat
^ copy-pasted from my lab slides

**Comment by jethrokyq** [comment]
Hi Adeline, just to add to Azelaze's answer, consider adding an additional predicate `index + 2 >= array.length` so that you can catch the edge case where you have two adjacents at the end of the array so that array[index] != array[index+2] will not be evaluated and throw index error.

**Comment by AdelineWongg** [comment]
Thank you! @jethrokyq

**Comment by cf6600** [comment]
I used distinct first to allow only unique digits in the stream, and later compared it to the stream with duplicates, and mapped the distinct list to the occurrence of each digit instead. Then you can just use predicate of x -> x > 1 to filter and represent more than 1 occurence in initial stream.

**Comment by markwty** [comment]
There are 2 ways to do it.
One as what @azelaze said and another
By taking the difference of the sequence and its first offset. 
For example, for sequence (1,2,2,3,3,3,4,4), the difference sequence is (1,2,2,3,3,3,4)-(2,2,3,3,3,4,4)=(-1,0,-1,0,0,-1,0)
Then count the no. of 0 sequences. This is beneficial in the sense that no need to considered 2 indexes before.
This difference sequence can be mapped to a pair with (count initialised to 0, isZero initialised to false) and reduce accordingly and add the count whenever there is a switch between non-zero to 0.
And if you are lazy to create the pair class, the pair can be represented as an integer i.e. count*10+(isZero)?1:0 and reduce and extract accordingly afterwards.
