### ISSUE TITLE
Combiner in Reduce Method

### ISSUE THREAD

**Issue by oliverguicw** [nus-cs2030/2021-s2#130]
# Description
I'm having trouble understanding why the below code does not work: 
For example, I want to convert a stream of strings into a stream of integers (by doing string.length()), however I cannot do .reduce(0, (ints, string) -> ints + string.length()) but this leads to a compile error: int cannot be converted to java.lang.String. Is there any way to resolve this?

## Topic:
Streams

## Screenshots

Screenshots (if any)

**Comment by oliverguicw** [comment]
How do I resolve this issue then? Any suggestions?

**Comment by shuenj** [comment]
Currently you might be using- reduce (T identity, BinaryOperator<T> accumulator)
Try using the 3 argument reduce:
reduce (U identity, BiFunction<U, ? super T, U> accumulator, BinaryOperator<U> combiner)
Hopefully this helps! :)

**Comment by oliverguicw** [comment]
oh okkk so I will be using the inherently parallelizable reduce function
thank you :)
