### ISSUE TITLE
Cyclic dependency Customer and Server

### ISSUE THREAD

**Issue by shuenj** [nus-cs2030/2021-s2#131]
# Summary
Cyclic dependency for Customer and Server classes

## Description 
For project level 1, I'm having an error of cyclic dependency between Customer and Server. Customer having a server when in SERVE state. And Server having a queue of customers. Are there any suggestions/recommendations for alternative OOP design?

## Screenshots (if any): 
Insert Images here if necessary

**Comment by gableejh** [comment]
I believe there's a cyclic dependency due to your customer containing a server and vice versa, however there is no need to pass in a server to the customer. That should remove the cyclic dependency on one another

**Comment by oliverguicw** [comment]
I think you can refer to the recitation 3 where prof used one of the student's problems. To avoid a cyclic dependency, I think you can create an association class which is the event class and have the event take in a server and customer.

**Comment by shuenj** [comment]
Alright, thank you! @gableejh @oliverguicw
