### ISSUE TITLE
Is it possible to remove elements from stream

### ISSUE THREAD

**Issue by AdelineWongg** [nus-cs2030/2021-s2#132]
How do I remove elements from a stream without using filter?

**Comment by High325** [comment]
you can use ```.skip(long n)``` to remove the first n elements of the stream

**Comment by Atem729** [comment]
I think .skip() will achieve ur intended objective! Alternatively, .limit() can be used to restrict the number of outputs

**Comment by Jjjetplane** [comment]
you can use the `.skip(n)` method which is an intermediate operation that discards the first n elements of the stream!
