### ISSUE TITLE
Project Level4

### ISSUE THREAD

**Issue by OuaisBien** [nus-cs2030/2021-s2#133]
# Summary
codecrunch test case 4.3

## Description 
At first I got

<img width="385" alt="Screenshot 2021-03-31 at 18 15 30" src="https://user-images.githubusercontent.com/77609596/113129171-2c66be00-924d-11eb-9238-54965f77595a.png">

then I realised I might have to remove a `restLength` when a customer left without being served.
But then I got something worse,

<img width="400" alt="Screenshot 2021-03-31 at 17 00 00" src="https://user-images.githubusercontent.com/77609596/113119134-ac3b5b00-9242-11eb-9ac5-22ec97a2b9ce.png">

Anyone run into this too?

**Comment by gableejh** [comment]
You do not need to explicitly remove a restLength as the server rest time is not tied to a customer, only after a Done event, then it takes the next restLength to evaluate if the server needs to rest. If a customer leaves, there is no need to do anything to the restLength

**Comment by OuaisBien** [comment]
yea i kinda get that. just the fact that no one left without being served in test case 2 and i passed it left me no choice...

**Comment by seancxy** [comment]
I'm not really sure about your implementation, but when wait events -> serve events, you might need to "reschedule" a customer to a later time if the server is resting
