### ISSUE TITLE
Project level 4 Case 3

### ISSUE THREAD

**Issue by jethrokyq** [nus-cs2030/2021-s2#144]
# Summary
Hi, does anyone have any insight into the inputs for 4.3, I'm not sure why my server assignment isn't working as intended? The general idea for my design is within an ArriveEvent, it will fetch the best server from the list of available servers based on a compareTo method implemented within the Server. Depending on state of the server that was fetched, it will call the next event accordingly. This has been working until test case 4.3 , and I'm not sure how to debug without the given inputs to figure out the state of the servers.
## Description 
```
   public int compareTo(Server server) {
        if ((this.available && !this.resting)  && (!server.available || server.resting)) {
            return -1;
        } else if ((!this.available || this.resting) && (server.available && !server.resting )) {
            return 1;
        } else if ((this.available && !this.resting) &&  (server.available && !server.resting)) {
            return this.id - server.getId();
        } else {
            if (this.id < server.getId() && !isQueueFull()) {
                return -1;
            } else {
                return 1;
            }
        }
    }
```

## Screenshots 

![image](https://user-images.githubusercontent.com/37759922/113435214-f1af8200-9414-11eb-9b23-ac401225f620.png)

**Comment by bonsibyl** [comment]
I had the same issue for awhile but i realised that it was because when i triggered my rest event, i scheduled a serve event based on next person in queue but this frees up a space in the server wait queue BEFORE the scheduled serve event triggers

**Comment by jethrokyq** [comment]
Thank you! @bonsibyl
