### ISSUE TITLE
Interpret Cyclical Dependencies Error output

### ISSUE THREAD

**Issue by ryantanjh** [nus-cs2030/2021-s2#149]
I am having difficulties identifying the cyclical dependencies in my code. How do I interpret this error output to help me with identifying the issues? 

Cyclic dependencies detected within:
ArrivalEvent.class -> Event.class
ArrivalEvent.class -> EventMachine.class
ArrivalEvent.class -> EventQueue.class
ArrivalEvent.class -> LeaveEvent.class
ArrivalEvent.class -> ServeEvent.class
ArrivalEvent.class -> WaitEvent.class
DoneEvent.class -> Event.class
DoneEvent.class -> EventMachine.class
DoneEvent.class -> EventQueue.class
Event.class -> EventMachine.class
Event.class -> EventQueue.class
EventComparator.class -> Event.class
EventMachine.class -> Event.class
EventMachine.class -> EventQueue.class
EventQueue.class -> Event.class
EventQueue.class -> EventComparator.class
LeaveEvent.class -> Event.class
LeaveEvent.class -> EventMachine.class
LeaveEvent.class -> EventQueue.class
Main1.class -> ArrivalEvent.class
Main1.class -> Event.class
Main1.class -> EventMachine.class
Main1.class -> EventQueue.class
Main2.class -> ArrivalEvent.class
Main2.class -> Event.class
Main2.class -> EventMachine.class
Main2.class -> EventQueue.class
ServeEvent.class -> DoneEvent.class
ServeEvent.class -> Event.class
ServeEvent.class -> EventMachine.class
ServeEvent.class -> EventQueue.class
WaitEvent.class -> Event.class
WaitEvent.class -> EventMachine.class
WaitEvent.class -> EventQueue.class
WaitEvent.class -> ServeEvent.class

**Comment by yuyitan** [comment]
There are definitely cyclic dependencies detected between these classes:
1. EventMachine and Event
2. Event and EventQueue
so you can start by fixing them first! For example, if your EventMachine has an event or methods taking in an event, your Event class cannot have an EventMachine or have methods taking in an EventMachine.
