### ISSUE TITLE
Setting up Checkstyle (Windows): Where are the files downloaded to after using wget?

### ISSUE THREAD

**Issue by jeremyojf** [nus-cs2030/2021-s2#15]
# Setting up Checkstyle
Where are the files downloaded to after using wget?

I did the 2 wget commands and I'm stuck there.

![image](https://user-images.githubusercontent.com/78136339/106153416-7c77c480-61b9-11eb-804e-8cde241b4077.png)

**Comment by Yung-Jer** [comment]
Your files will be at the current directory.

**Comment by gableejh** [comment]
Yes, it should be in your current directory, type "ls" to see the files.

**Comment by jeremyojf** [comment]
I was actually asking how to find the current directory. Anyway I found out it can be accessed through:
C:\Users\<username>\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\<username>

**Comment by jeremyojf** [comment]
I was actually asking how to find the directory. Anyway I found out it can be accessed at:
C:\Users\username\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\username
