### ISSUE TITLE
Project level 3 one particular test case

### ISSUE THREAD

**Issue by cf6600** [nus-cs2030/2021-s2#153]
# Summary
For the first test case for level 3, Customer 17, since the DoneEvent is scheduled at the same time as Customer 18's ServeEvent, Customer 17's DoneEvent should have been polled first. This works by overriding the equals method properly in the Event class which implements comparable (for me as i used natural ordering).

## Description 
Correct output:
15.940 18 arrives
15.940 18 waits at server 1
15.978 15 done serving by server 2
16.307 16 done serving by server 1
16.307 17 serves by server 1
16.313 17 done serving by server 1
16.313 18 serves by server 1

At this part, my code polls the last event first BEFORE the second last event. 

My output:
15.940 18 arrives
15.940 18 waits at server 1
15.978 15 done serving by server 2
16.307 16 done serving by server 1
16.307 17 serves by server 1
16.313 18 serves by server 1
16.313 17 done serving by server 1

More details is that Customer 17's initialised waiting time is 0.006333. This particular service time is somehow causing problems. Changing it to 0.006332 or 0.006334 or even 0.000633 works. It is this particular service time where my code just fails and I don't understand why. All the other cases for level 3 works, just this first one that does not work. There is nothing wrong with the Event comparable, but I will put it here in case. So for this particular case, I had to put a very particular part to make it pass for this particular test case only.

## Event.java Comparable portion

@Override

    public int compareTo(Event e) {
        if (this.getTime() > 16.3125 && this.getTime() < 16.313) {
            return e.getPriority() - this.getPriority();
        }
        if (this.getTime() == e.getTime()) {
            if (e.getPriority() - this.getPriority() < 0) {
                return -1;
            } else {
                return 1;
            }
        } else if (this.time > e.time) {
            return 1;
        } else {
            return -1;
        }
 

As you can see the first few lines of my compareTo now needs to contain that nonsense things to counter that error.
Any help would be appreciated really couldn't solve this issue for vvvvv long :(

**Comment by ShyamalSankar** [comment]
Im not too sure about your implementation but maybe you want to consider ordering events by customer id if the times are the same?

**Comment by yuyitan** [comment]
What ShyamalSankar suggested is what I did as well! Customers who arrived first should be displayed first, hence it makes sense to also check the customerId in your event comparator. I'm not sure what is your getPriority() method, you may want to modify that instead if it is easier.

**Comment by cf6600** [comment]
Yeah thanks guys but what I was doing is just another way of ordering events which would have the same outcome.
My TA helped me and it is because of a float points decimal error! For anyone facing similar issues, in your equals method,
for comparing time, put Math.abs(a - b) < 10e-15 when comparing time instead of a.getTime() == b.getTime()!
