### ISSUE TITLE
'Method gcd is not defined with a single pipeline starting with return some stream...'

### ISSUE THREAD

**Issue by tyc001** [nus-cs2030/2021-s2#154]
Hello, whenever I submit my code for the GCD section of Lab6, I get this error. I don't have any idea what this means, or whether it is even a diagnosis of what's wrong or a prescription of what to do. For reference, these are the 2 methods for which I got this error in CodeCrunch:

`    static int gcd(int m, int n) {
        if (m == n) {
            return m;
        }

        int greater = m > n ? m : n;
        int lesser = m > n ? n : m;

        return Stream.<Integer[]>iterate(new Integer[]{greater, lesser}, arr -> arr[1] != 0,
            arr -> new Integer[]{arr[1], arr[0] % arr[1]}).filter(arr -> arr[0] % arr[1]
                == 0).findFirst().get()[1];`

**Comment by cf6600** [comment]
I got this error once too, its because your code must start with return Stream........bla bla bla. Meaning your int greater and int lesser thing cannot use! Have to find a way to implement it in your stream. Just an extra condition added by the TAs or prof i think.

**Comment by tyc001** [comment]
> I got this error once too, its because your code must start with return Stream........bla bla bla. Meaning your int greater and int lesser thing cannot use! Have to find a way to implement it in your stream. Just an extra condition added by the TAs or prof i think.

LOL incredible. Thanks so much for answering my question at 2+am!!

**Comment by tyc001** [comment]
Erm, apologies for reopening but I did this code and it still didnt work: 

`static int gcd(int m, int n) {
        Stream<Integer[]> stream = Stream.<Integer[]>iterate(new Integer[]{m > n ? m : n,
            m > n ? n : m}, arr -> arr[1] != 0, arr -> new Integer[]{arr[1], arr[0] %
                arr[1]}).filter(arr -> arr[0] % arr[1] == 0);

        return stream.findFirst().get()[1];`

**Comment by cf6600** [comment]
I think you have to return a stream straightaway, so cannot create it first.
So I think just put .findFirst().get()[1] at the end of ur code and just straightaway return, should work. However, you might get the error saying you can't use arrays, cos at first i used arrays n it didn't work, so I had to create a custom Pair class....

**Comment by tyc001** [comment]
Alright, finally solved it, thanks so much!
