### ISSUE TITLE
Project Level 4 Advice Needed

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#159]
# Summary
I have been trying to implement the server rest times but I encountered some issues passing the additional test cases. I've passed all the test cases up to 4-3. However, we do not have access to these additional test cases and it would be very inefficient to keep resubmitting on Codecrunch. Can anyone help advise on how I may go about resolving this issue? Thanks! 

## Screenshots (if any): 

<img width="602" alt="Screen Shot 2021-04-04 at 6 29 38 PM" src="https://user-images.githubusercontent.com/77650951/113505814-c4c5b100-9573-11eb-9c0f-aad5692b839b.png">

**Comment by Zekeseoj** [comment]
What you probably want to do is to check if ur previously queued serve event's eventTime matches/not matches with the current server's avail Time. e.g.  eventTime for old serve event is earlier than current server 's avail time (included with rest time as well). Doing so , you can then recreate new serve Events that factor in the rest time given to that current server. Hope it helps!

**Comment by yuyitan** [comment]
> What you probably want to do is to check if ur previously queued serve event's eventTime matches/not matches with the current server's avail Time. e.g. eventTime for old serve event is earlier than current server 's avail time (included with rest time as well). Doing so , you can then recreate new serve Events that factor in the rest time given to that current server. Hope it helps!

Thanks, I edited my code with your method and that helped me with the previous problem! However, my code failed the additional test cases (which we do not have access to) so I'm kind of stuck right now. :(

**Comment by Zekeseoj** [comment]
It might help u to consider two new events, restEvent and server Back event. If I'm not wrong, you probably missed something out when u separated ur sequences with a rest event alone.

**Comment by gableejh** [comment]
Not too sure about your implementation but based on your screenshot where 2 customers are served by server 1 at the same time, seems like your Serve event is pre-scheduled and will run regardless. Perhaps there needs to be an additional check to ensure that the server is available, not taking a rest nor serving a customer before initiating the serve event, otherwise, the event should be rescheduled based on the server's next available time.

**Comment by yuyitan** [comment]
Thanks @Zekeseoj and @gableejh ! I added the ServerBack event and made some improvement to my code. It turned out that I forgot to add the customer's serviceTime to the server's availTime when I reschedule the event (oops).

**Comment by dumbasssoul** [comment]
> Doing

how do you go about doing this?

**Comment by dumbasssoul** [comment]
> What you probably want to do is to check if ur previously queued serve event's eventTime matches/not matches with the current server's avail Time. e.g. eventTime for old serve event is earlier than current server 's avail time (included with rest time as well). Doing so , you can then recreate new serve Events that factor in the rest time given to that current server. Hope it helps!

how do you go about doing this?
