### ISSUE TITLE
Files downloaded from CodeCrunch on read-only/permission denied

### ISSUE THREAD

**Issue by wuchuank** [nus-cs2030/2021-s2#16]
After downloading files for Lab 1 from CodeCrunch, i moved them to my home directory of Ubuntu through C:\Users\NAME\AppData\Local\Packages\DISTRO_FOLDER\LocalState\rootfs\home. 

However, when i attempt to edit the files through Ubuntu, Vim tells me that permission denied. Tried accessing using the root and the files are still in read-only and i must add a ! everytime i write and quit from vim. 

Is there any way to change the state of the files to whereas though they have been created in Ubuntu like normal?

**Comment by vjo-anne209** [comment]
My TA suggested a temporary solution for this. He told to me to write sudo vim filename.java to open the file. Then, you will get a warning that says that this file is a readonly file. So, when I tried to save the file again after editing it, he told me to type :w! (It forces vim to edit a readonly file).

**Comment by KaveenE** [comment]
This might help you: 
https://github.com/nus-cs2030/2021-s2/issues/8#issue-788589319

**Comment by wuchuank** [comment]
I see. Thanks for all the help! 😃
