### ISSUE TITLE
Do we have to care about unsafe operations? Level 3 of Lab07

### ISSUE THREAD

**Issue by Cassianky** [nus-cs2030/2021-s2#164]
# Summary of Problem
Upon inserting my Logger and LoggerImpl classes into Jshell, there will be a prompt for unsafe operations like unchecked conversion. I'm not too sure what this means. But my code can compile and output correctly so I'm concerned if the presence of these unsafe operations is okay anot. Thank you in advance. An example in shown in the screenshot below. 

Screenshot
<img width="584" alt="Screenshot 2021-04-04 215051" src="https://user-images.githubusercontent.com/77654564/113511677-9788fb00-9593-11eb-8622-19d7bb8c1df8.png">

**Comment by jethrokyq** [comment]
Hi, I believe all you need to add is 
`new LoggerImpl<T>(t, queue)`

**Comment by markwty** [comment]
Without specifying T, new LoggerImpl(t, queue) can be interpreted as new LoggerImpl<? super T>(t, queue) (anything that super T can be in the angular brackets) so there is ambiguity on what is returned. Although the compiler will choose LoggerImpl<T> and seemingly nothing is wrong, it is still a good practice to specify.

**Comment by ivankqw** [comment]
Conceptually, this is type inference which prof has mentioned in either lecture 7/8, fyi :)

**Comment by Keithlimhs** [comment]
To answer your question, the presence of these unsafe operations are not very good, as it shows that there is no clear type given, hence there is a need to remove such unsafe operations. As what others have commented above, you can simply specify the generic < T >
