### ISSUE TITLE
Lab 7 Level 3 "raw types" checkstyle warning

### ISSUE THREAD

**Issue by eugenelimnus** [nus-cs2030/2021-s2#165]
# Summary

I am having some trouble with level 3 as the codecrunch checkstyle tells me that I am using rawtypes (generics without a class stated), however where I try to typecast into my generic classes like Logger and ImList (even if I use Object class), it gives me the unchecked cast error, and if Im not wrong codecrunch does not allow @SuppressWarnings("unchecked") either. Any advice on how to work around this raw type warning?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![CS Lab7 error](https://user-images.githubusercontent.com/77771438/113535768-ec198e00-9606-11eb-98cb-0febc31b044f.JPG)

**Comment by e0543492** [comment]
I think the problem is that you need to specify the generic type, even in the typecast since your Logger<T> class is a generic class. At least that was what I did.

**Comment by Keithlimhs** [comment]
Hi you need to include what is the generic type for the ImList and Logger

**Comment by clementyee303** [comment]
You could assign to `Logger<?>`

**Comment by gerarara** [comment]
you need to include the generic type (`<T>`) for the logger, e.g. `Logger<Object>`, `Logger<Integer>`, `Logger<?>`, etc.

**Comment by eugenelimnus** [comment]
Update:
I used <?> and @SuppressWarnings("unchecked") at that specific method only, thanks for your comments!

**Comment by clementyee303** [comment]
> 
> 
> Update:
> I used <?> and @SuppressWarnings("unchecked") at that specific method only, thanks for your comments!

Hey just a heads up, since I'm assuming this is for your equals method, you should just check if obj is instanceof logger. Since you're doing a wildcard typecast there is no need for @SuppressWarnings. Also codecrunch does not allow it for this specific lab.
