### ISSUE TITLE
FlatMap lvl 4

### ISSUE THREAD

**Issue by Zekeseoj** [nus-cs2030/2021-s2#166]
# Summary
I am having trouble passing this test case for lvl 4 : Logger.make(5).flatMap(x -> Logger.make(x)).equals(Logger.make(5))
From this test case, it seems to be that flatmap would return the same logger object which is Logger.make(5) in this case.
My return type for flatMap is LoggerImpl<U>, so my issue is that i do not know how to ensure that im able to return the same logger object when such a flatMap(x -> logger.make(x)) is called.

## Description:
My return constructors basically takes in a string type Immutable List (i.e ImList<string> from lecture). This helps me to retrieve my output for printlog(). I thought of checking (this.value == function.apply(this.value).getValue()) to identify when to 'return' the same log object but I'm not sure how to return it per say.

## Code Snippets

Attach code snippets (if any)
![flatmap](https://user-images.githubusercontent.com/77658282/113541856-a0baac00-9615-11eb-819c-045c64badb4b.png)
![flatmap2](https://user-images.githubusercontent.com/77658282/113542300-8d5c1080-9616-11eb-83cf-c0205d9dbd68.png)

## Screenshots

Screenshots (if any)

**Comment by isaactyj** [comment]
I think that it might be your equals method. I don't think that's the only issue with the flatmap. Do you want to show how you compare?

**Comment by Zekeseoj** [comment]
@isaactyj  yea sure
![equals](https://user-images.githubusercontent.com/77658282/113549080-550eff00-9623-11eb-8ffd-6a24f8b4bf62.png)

**Comment by isaactyj** [comment]
Okay at least it should be other instanceof LoggerImpl i think and why are you still comparing the memory address in the else if? You should be comparing the logs and the obj/value inside not sure how did this slipped past the Map testcase but try changing the things I said you should pass the particular test case

**Comment by Zekeseoj** [comment]
it still returns false. also are u referring to this == logger in 2nd else if statement? This is to help me check if the logs instances are the same. 
![xx](https://user-images.githubusercontent.com/77658282/113550001-edf24a00-9624-11eb-9e83-8c5efdc712a0.png)

**Comment by isaactyj** [comment]
U checked if its a loggerImpl but you still went to convert it to a logger which is not needed. you are still not checking your object inside and your outputs. Unless your value and output are exactly the same then it should return false.

**Comment by Zekeseoj** [comment]
sry i dont understand what you are trying to say. Mind clarifying where in my code could be the issue?

**Comment by isaactyj** [comment]
Did you compare the statements or in this case your Imlist? you never compared your imlist to check if they have the same things right?

**Comment by Zekeseoj** [comment]
ahhhh i think i solved it. (this == logger) was a major reason why I'm wrong, coupled with not checking for my ImList. Thanks @isaactyj!

**Comment by isaactyj** [comment]
Does the flatmap give the correct output tho? I tried your method but its missing the new value 7 for the b

**Comment by Zekeseoj** [comment]
I'm stuck for that. My implementation is not correct.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by isaactyj** [comment]
![lab07](https://user-images.githubusercontent.com/77622789/113571315-c1502980-9648-11eb-8670-36b772a343f8.JPG)

Somehow your code takes the second last flatmap and not the last flatmap

**Comment by Zekeseoj** [comment]
@isaactyj did u managed to solve it?

**Comment by Cassianky** [comment]
I think the reason the code is not outputting the new value 7 for the b is that the flatMap's function.apply may generate a printlog list that is like initialization new, changed A, changed B. You have to take into account the original printlog's initialization old, changed C. Then combine them to form initialization old, changed C, changed A and changed B in this order. 

for Logger<Integer> b = Logger.make(5).flatMap(x -> Logger.make(x).map(y -> y + 2).flatMap(y -> Logger.make(y).map(z -> z * 10))), the this.list you're referring to in flatMap is the Logger.make(y)  which is not correct.

**Comment by isaactyj** [comment]
@Zekeseoj Yes i did! you just need to realise that your method already calls map but in this case you are also calling map twice first in your prompt line and once again in your return line

**Comment by darylyeejh** [comment]
yes, as mentioned by @Cassianky , you have to add the older logs rather than just the object (in this case the object is 70), if not the 7 would be 'forgotten'

**Comment by Zekeseoj** [comment]
ohh okok got it thanks!
