### ISSUE TITLE
Lab 7 flatMap

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2030/2021-s2#181]
# Summary

In lab 7 level 4, this code
```
Logger<Integer> a = Logger.make(5).flatMap(x -> Logger.make(x).map(y -> y + 2)).flatMap(y -> Logger.make(y).map(z -> z * 10))
a.printlog()
```
gives the following output
```
Value initialized. Value = 5
Value changed! New value = 7
Value changed! New value = 70
```
I can't understand why.
In my understanding, `Logger.make(5)` gives `Logger[5]`. The first `flatMap` maps the value `5` to `Logger[7]` whose log contains 5 and 7. Then, the second `flatMap` should take the value of `Logger[7]`, which is `7`, and make a new `Logger[7]`. This new `Logger[7]` should have no record of `5` because it is newly created by `Logger.make()`. After that, it is mapped to `Logger[70]` whose log contains 7 and 70. Thus, my expected output is
 ```
Value initialized. Value = 7
Value changed! New value = 70
```
Can anyone help me see the problem? Thanks!

**Comment by hendricksgin** [comment]
Hi, I'm still trying to figure things out myself but maybe this might help: https://github.com/nus-cs2030/2021-s2/issues/177

**Comment by OuaisBien** [comment]
I think generally your reasoning is correct, just that the way they chose to have us implement required us to keep track of the history of values from all maps no matter inside or outside the flatMap. So the printlog() before the second flatMap is
```
Value initialized. Value = 5 
Value changed! New value = 7
```
after the second flatMap it becomes
```
Value initialized. Value = 5 
Value changed! New value = 7
Value changed! New value = 70
```

**Comment by zihaowrez** [comment]
My question is answered in the recitation. Thanks!
