### ISSUE TITLE
Lab 7 level 3 - symbol printlog and map cannot be found

### ISSUE THREAD

**Issue by AdelineWongg** [nus-cs2030/2021-s2#187]
I implemented my map and printlog methods both in my loggerImpl. 
my map function will return a <U> Logger<U> when map(Function<? super T, ? extends U> mapper ) is applied.
Although I declared Logger as the return output, my return statement will return a new LoggerImpl.
I can't seem to understand why I cannot call map and printlog when it is already in my loggerImpl.

**Comment by gableejh** [comment]
Did you include both methods in Logger.java? e.g.
`public <U> Logger<U> map(Function<? super T, ? extends U> func);`

**Comment by AdelineWongg** [comment]
Oops I did not declare in my interface. Works now. Thanks!

**Comment by gableejh** [comment]
No worries!
