### ISSUE TITLE
printlog() method

### ISSUE THREAD

**Issue by joleneleee** [nus-cs2030/2021-s2#188]
newstring = newstring + "\nValue unchanged. Value = " + this.object;

I am unable to return the string with a new line break, my output is Value initialized. Value = 0\nValue changed! New value = 1\nValue changed! New value = 3\nValue changed! New value = 6 for example.

How do I return a new line

**Comment by magiciansz** [comment]
Hi joleneleee!

I am not sure if my method is correct but what I did was different, I stored all the strings each time you map into a ArrayList, including when you first initialize the Logger. So my printlog() method is a void that does a for loop, printing the elements in the ArrayList one by one on a new line.
Hope this helps!
@keithlimhs @gwajoon @jettevy I heard the boys got a method for a string printlog() method?

**Comment by gableejh** [comment]
my printlog() method is void as well, `this.logs.stream().forEach(element -> System.out.println(element));`

**Comment by radellng** [comment]
Hi joleneleee!

I did exactly the same as magiciansz, for convenience sake using an ArrayList<String>, strings can be added into the ArrayList easily whenever necessary. My printlog() method is printing each String in the ArrayList, however i used streams which is basically the same as a for-loop like magiciansz.

**Comment by Jeyxiang** [comment]
Hi I think you can try `System.out.println(newstring)` , your new line break should work just fine, however instead of returning a String it will just be a void method :>

**Comment by jordanwwb** [comment]
hi, if im not wrong the line break will not work if you return it as a String. However typing it out in a System.out.println(log) would be able to execute the line break. For this exercise, it would be easier to store the logs in a ArrayList<String>. Then the printlog() method would be a void method printing the logs one by one using a for loop.

**Comment by dumbasssoul** [comment]
the solutions for level 1, 3 and 4 are discussed during todays recitation btw!

**Comment by yokester98** [comment]
This is the implementation for printlog() covered in today's recitation.

`void printlog() {
    this.log.stream().forEach(x -> System.out.println(x));
}`

**Comment by Jason-Ng00** [comment]
newstring = newstring + "\nValue unchanged. Value = " + this.object;
I did the same thing as you but it could not work, my solution was just simply print out the log instead of returning it.

**Comment by brennanleez-coder** [comment]
> unable to return the string with a new line break, my output is Value initialize

Hi jolene you can try to break it up. meaning "\n" + "Value changed!...."

**Comment by e0543492** [comment]
Your can try newstring = newstring + "\n" + "Value unchanged. Value = " + this.object;

**Comment by ck-109** [comment]
I feel it is always a good practice to use List to store any updates.
Easier for you to access the different state via list indexing also.

**Comment by SrinivasG99** [comment]
Breaking it up to "\n" + "Vale unchanged." should work, but I feel using a list of string is an easier implementation.

**Comment by i-sack** [comment]
Personally, I feel using an ArrayList to store your strings and printing each string out individually through the use of forEach(System.out.println()) is much better as it not only keeps all ur strings in one place but also settles the different lines.
