### ISSUE TITLE
CodeCrunch Testcases

### ISSUE THREAD

**Issue by jeromesjj08** [nus-cs2030/2021-s2#19]
I am able to print all the expected output on vim. But codecrunch returns me a "Incorrect output" any idea how to solve this. 

Screenshot
![Lab01](https://user-images.githubusercontent.com/78015920/106356788-2764bb80-633d-11eb-9d5d-7eca02874010.jpg)

**Comment by TeddYE** [comment]
You are not returning the correct output. If you look carefully, you will see that your outputs are reversed.

**Comment by danikrisdayadi** [comment]
Yep as what @TeddYE mentioned. If you didn't see it, your test 
`jshell> new Point(0, 0).moveTo(new Point(0, 0).angleTo(new Point(-1, 0)), 1.0)` has an output of `-1.1570796326` when instead it should be `3.1415926`

**Comment by jeromesjj08** [comment]
Yeap, I got it. I just realised it. Thanks man!=)
