### ISSUE TITLE
Level 4 of PA2

### ISSUE THREAD

**Issue by chamath2030** [nus-cs2030/2021-s2#195]
how do i go about creating the static of method, i'm really lost...

**Comment by cf6600** [comment]
Very confused as _of_ is a static method...however it takes in a lambda that does something to the s when not paired with a flatmap, which should throw an error since s has no reference, so in that case we need to print string "Aggregate", but are we supposed to do this by catching an exception? Since _of_ is supposed to return an Aggregate and not a string.

**Comment by Deshun99** [comment]
i think it have something to do with the Optional.ofNullable, it takes in a Function<T,Aggregate<S,T>>, so if the function is empty, it would return an Optional.empty

**Comment by OuaisBien** [comment]
Actually we don't need any Optional or Exception. Try to create a static `of` method that takes in a `Function` and returns a new `Aggregate` and a field `private final Function<S, Pair<S,T>> f;`. After that u will need to create another method in `Aggregate`, in my case `private Pair<S,T> apply(S stuff)`. Apply `stuff` to `f` and a `Pair<S,T>` is returned, with which u acquire the the required `new Aggregate<S,U>(pair.first(), pair.second())` for `flatMap(Function<T, Aggregate<S,U>> f))`. This way it returns you a `Aggregate` object with merely a lambda initialised when you call the `of` method directly and perhaps you can check it and return "Aggregate" in `toString()`.

**Comment by jamesmakjxnp** [comment]
> Actually we don't need any Optional or Exception.
But how to return Invalid Argument string without exceptions? Where should we check if map or flatmap is called wrongly?

**Comment by OuaisBien** [comment]
When the `seed` method is called i get an `Aggregate` with only a seed, no object, no Function. Check what the `Aggregate` object has in flatMap() and map(). Basically I return a new Aggregate with no argument if `this` only has a seed and set its `boolean isInvalid` to be true. And I check in toString() if it has a seed, if it has an object, if it's invalid, if it has a function, depending on the situation, "Aggregate", "Invalid Aggregate" or other regular toString is returned. I'm not even sure if you can return the exact string"Invalid Aggregate" if it is done through exception.

**Comment by clementyee303** [comment]
> 
> 
> Actually we don't need any Optional or Exception. Try to create a static `of` method that takes in a `Function` and returns a new `Aggregate` and a field `private final Function<S, Pair<S,T>> f;`. After that u will need to create another method in `Aggregate`, in my case `private Pair<S,T> apply(S stuff)`. Apply `stuff` to `f` and a `Pair<S,T>` is returned, with which u acquire the the required `new Aggregate<S,U>(pair.first(), pair.second())` for `flatMap(Function<T, Aggregate<S,U>> f))`. This way it returns you a `Aggregate` object with merely a lambda initialised when you call the `of` method directly and perhaps you can check it and return "Aggregate" in `toString()`.

How do you create a new Aggregate with just the Function attribute without initializing the seed attribute?

**Comment by clementyee303** [comment]
> 
> 
> Actually we don't need any Optional or Exception. Try to create a static `of` method that takes in a `Function` and returns a new `Aggregate` and a field `private final Function<S, Pair<S,T>> f;`. After that u will need to create another method in `Aggregate`, in my case `private Pair<S,T> apply(S stuff)`. Apply `stuff` to `f` and a `Pair<S,T>` is returned, with which u acquire the the required `new Aggregate<S,U>(pair.first(), pair.second())` for `flatMap(Function<T, Aggregate<S,U>> f))`. This way it returns you a `Aggregate` object with merely a lambda initialised when you call the `of` method directly and perhaps you can check it and return "Aggregate" in `toString()`.

How do you create a new Aggregate that does not initialise private final Seed attribute?

**Comment by clementyee303** [comment]
> 
> 
> Actually we don't need any Optional or Exception. Try to create a static `of` method that takes in a `Function` and returns a new `Aggregate` and a field `private final Function<S, Pair<S,T>> f;`. After that u will need to create another method in `Aggregate`, in my case `private Pair<S,T> apply(S stuff)`. Apply `stuff` to `f` and a `Pair<S,T>` is returned, with which u acquire the the required `new Aggregate<S,U>(pair.first(), pair.second())` for `flatMap(Function<T, Aggregate<S,U>> f))`. This way it returns you a `Aggregate` object with merely a lambda initialised when you call the `of` method directly and perhaps you can check it and return "Aggregate" in `toString()`.

How do you create a new Aggregate that does not initialise private final S seed / private final Function f? (without using Optional as you mentioned) I think we probably did a similar method, although I used Optional (since I wasn't sure codecrunch allowed the use of null)

**Comment by OuaisBien** [comment]
yes, `null` is allowed.

**Comment by adellelimrj** [comment]
> > Actually we don't need any Optional or Exception.
> 
> But how to return Invalid Argument string without exceptions? Where should we check if map or flatmap is called wrongly?

I would suggest adding in a new property that'll indicate whether the incoming seed/ object is null. this way, at the toString() method, you can check if the indicator is false, and if it is, then return the "invalid aggregate". not sure if there's a better method that won't require so much changes though... because this requires a new constructor.

**Comment by chamath2030** [comment]
thanks Githubbers @OuaisBien @adellelimrj , can I ask if you create an "InvalidAggregate.java" file to handle the invalid aggregate? Is it necessary? or can just make do within the Aggregate.java file itself

**Comment by OuaisBien** [comment]
nope, i don't have another `InvalidAggregate`. Everything is in `Aggregate`.

**Comment by adellelimrj** [comment]
I did not create an extra file! I think Aggregate.java is sufficient

**Comment by Martini-Chwang** [comment]
Yepp same here! Aggregate.java is able to act as an invalid aggregate as well!

**Comment by chamath2030** [comment]
> Actually we don't need any Optional or Exception. Try to create a static `of` method that takes in a `Function` and returns a new `Aggregate` and a field `private final Function<S, Pair<S,T>> f;`. After that u will need to create another method in `Aggregate`, in my case `private Pair<S,T> apply(S stuff)`. Apply `stuff` to `f` and a `Pair<S,T>` is returned, with which u acquire the the required `new Aggregate<S,U>(pair.first(), pair.second())` for `flatMap(Function<T, Aggregate<S,U>> f))`. This way it returns you a `Aggregate` object with merely a lambda initialised when you call the `of` method directly and perhaps you can check it and return "Aggregate" in `toString()`.

@OuaisBien hi thank you so much for your help. i'm trying to do up the flatmap method but can't seem to get it to work. can you please advise and how use the Pair<S,T> to return a new Aggregate<S,U> since T and U are different types? 

`public <U> Aggregate<S,U> flatMap(Function<T,Aggregate<S,U>> func) {
		Aggregate<S,U> agg = func.apply(this.getObject());
		Pair<S,T> pair = this.f.apply(this.seed);
		S firstObj = pair.getFirstObj();
		U secondObj = (U) pair.getSecondObj();
		return new Aggregate<S,U>(firstObj, secondObj);
	}`

here are my constructors 
`private final S seed;
	private final T object;
	private final Function<S,Pair<S,T>> f;

	public Aggregate(S seed, T object) {
		this.seed = seed;
		this.object = object;
		this.f = null;
	}

	public Aggregate(S seed) {
		this.seed = seed;
		this.object = null;
		this.f = null;
	}

	Aggregate(Function<S,Pair<S,T>> f) {
		this.seed = null;
		this.object = null;
		this.f = f;
	}`


and here is my static of method
`public static <S,T> Aggregate<S,T> of(Function<S,Pair<S,T>> func) {
		return new Aggregate<S,T>(func);
	}`

**Comment by OuaisBien** [comment]
I think the problem is that instead of Pair<S,T> it should be Pair<S,U> in your case since <S,U> in Aggregate<S,U> and Pair<S,U> are guaranteed to be the same. Also, did you use your agg (`Aggregate<S,U> agg = func.apply(this.getObject());`)?

**Comment by chamath2030** [comment]
> I think the problem is that instead of Pair<S,T> it should be Pair<S,U> in your case since <S,U> in Aggregate<S,U> and Pair<S,U> are guaranteed to be the same. Also, did you use your agg (`Aggregate<S,U> agg = func.apply(this.getObject());`)?

hi @OuaisBien , really appreciate your help. My main parameters are <S,T>. created a `private final Function<S, Pair<S,T>> f`. I also created the extra method `private Pair<S,T> apply(S stuff)`. After applying the function to S, `f.apply(stuff)`, I believe it returns a `Pair<S,T>`. How do I convert this Pair<S,T> into Aggregate<S,U> since T and U are of different type?

**Comment by OuaisBien** [comment]
Exactly! T and U are different, for example `T` could be `String` and `U` could be `Integer`, and it will always be specified so just use `Pair<S,U> pair = func.apply(this.obj).apply(this.seed);`. Btw, rename your getFirstObj(), getSecondObj() to first() and second() or there will be some errors on Codecrunch.

**Comment by chamath2030** [comment]
> Exactly! T and U are different, for example `T` could be `String` and `U` could be `Integer`, and it will always be specified so just use `Pair<S,U> pair = func.apply(this.obj).apply(this.seed);`. Btw, rename your getFirstObj(), getSecondObj() to first() and second() or there will be some errors on Codecrunch.

@OuaisBien ahhh i got it, thanks @OuaisBien! huge shoutout to you
