### ISSUE TITLE
Project level 4_3

### ISSUE THREAD

**Issue by hewtungyuen** [nus-cs2030/2021-s2#196]
# Summary
Has anybody experienced this error before/ have any hints for test case 4_3? Thank you!

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/63499355/114213371-74948780-9995-11eb-81e6-3e59bc6a3685.png)

**Comment by brendancjz** [comment]
Hi there, it seems that the server should not be resting after serving customer 8 but yours did instead. Maybe you removed one too many rest times such that the server took the wrong rest time when it comes to customer 8. How is your rest times stored and how did you ensure the servers obtain the correct rest times?

**Comment by OuaisBien** [comment]
I think since you pass test case 4-2 you are assigning the correct rest length to servers. It might be some problem regarding updating the server rest length, getting the next available time or something between the transition of a done and a rest event. By the way this is a very thorny test case imo.

**Comment by hewtungyuen** [comment]
Thank you for the suggestions. @brendancjz I did not store my rest times in any form of data structure. Only after the execution of my DoneEvent, I used sc.nextDouble() to read in the rest time and assign it to the server in question.

**Comment by brendancjz** [comment]
Ah, I see. Sorry but I'm not sure how to help now. What I did was to get the rest times input into a queue DS. Then the Server class takes in this queue and when the rest time is needed, it will simply poll out the first one which will be the correct rest time.

**Comment by mickJirapat** [comment]
Hi! I was stuck at this test case for quite a while too (different errors). Try printing out the Events PQ as well as the Server List every time you return a new Event and see whether every Event is updated properly. The problem right now might be that your code is updating the time of Event in the PQ wrongly. Hope this helps!

**Comment by hewtungyuen** [comment]
Thanks everyone for the help!
