### ISSUE TITLE
level 4 issue with wait event

### ISSUE THREAD

**Issue by tiara2711** [nus-cs2030/2021-s2#199]
# Summary
I have problems with my wait event :( 

## Description 

Right now my wait event calls serve, so to account for the condition that the waiting customer isn't the first customer in the server's queue, I've done a loop to add all the service times of the customers before it together to get the start time of serve event. However, now that I have to account for rest times for each server, I'm not sure how to get the time to call the serve event since the queue of rest times are shared among all the servers. 
Is there a way to get how long the server will rest for after serving a particular customer?

## Screenshots (if any): 
Insert Images here if necessary

**Comment by Zekeseoj** [comment]
what i did was store all resting times into an arraylist and poll the first rest in line and assign it to the server that finishes serving its customer.
