### ISSUE TITLE
CodeCrunch Runtime exception detected. Instance/class Properties found in class.

### ISSUE THREAD

**Issue by OuaisBien** [nus-cs2030/2021-s2#201]
I don't get it. Everything works just fine on jshell.
<img width="1000" alt="Screenshot 2021-04-11 at 00 51 32" src="https://user-images.githubusercontent.com/77609596/114278060-84c56900-9a60-11eb-97aa-cf7d74d073df.png">

**Comment by KaveenE** [comment]
Do you happen to have an instance or class(static) field that is defined in your `Count` class but not in `Aggregate` class? That may be throwing this error

**Comment by OuaisBien** [comment]
hmmm , not sure. Here are my class fields. Can you tell whats wrong?
<img width="444" alt="Screenshot 2021-04-11 at 09 17 26" src="https://user-images.githubusercontent.com/77609596/114289004-fcb68200-9aa6-11eb-8d84-26095acfde75.png">
<img width="444" alt="Screenshot 2021-04-11 at 09 17 49" src="https://user-images.githubusercontent.com/77609596/114289005-fe804580-9aa6-11eb-9035-113f847b59f3.png">

**Comment by KaveenE** [comment]
Based on this: 
![image](https://user-images.githubusercontent.com/59110376/114294142-0e138480-9acf-11eb-9273-e5f4b654f0e0.png)

I'm guessing you shouldn't have any states in your `Count` class. Notice how those states in you `Count` class are also present in `Aggregate`? That's where you should utilise inheritance.

This is just my guess though, hope it helps.

**Comment by OuaisBien** [comment]
u r right! Thanks for your help!!!
