### ISSUE TITLE
Project level 2

### ISSUE THREAD

**Issue by wentinggy** [nus-cs2030/2021-s2#203]
hi friends, I'm not sure why for my level 2 test case 6 both customer gets served at the same time. However, I am only returning the serve event for one customer (?). Any idea why both customers get served concurrently? Thank you!
<img width="721" alt="Screenshot 2021-04-11 at 11 16 26 AM" src="https://user-images.githubusercontent.com/77621160/114291140-95ed9480-9ab7-11eb-83d7-759dfe29bcb8.png">
<img width="1097" alt="Screenshot 2021-04-11 at 11 20 37 AM" src="https://user-images.githubusercontent.com/77621160/114291194-f41a7780-9ab7-11eb-8c8e-81dc7390b051.png">

**Comment by jeremycte** [comment]
Hi @wentinggy, I faced the same issue but managed to solve it. Feel free to view the same issue here https://github.com/nus-cs2030/2021-s2/issues/107

**Comment by wentinggy** [comment]
ah thankyou!

**Comment by wentinggy** [comment]
> Hi @wentinggy, I faced the same issue but managed to solve it. Feel free to view the same issue here #107

Hi sorry i still can't solve the issue after looking at the thread :( It either works for level 1 and fails for level 2 or vice versa. How did you manage to overcome this issue?

**Comment by gwajoon** [comment]
Heylo @wentinggy I think it has to do with the updating of server status like that in @jeremycte's case! The fact that the server serves both Customer 9 and 10 at 10.484 means that the server appears to be 'available' to the system when it is polled from the queue. There probably is a small issue at one of your events which did not update the server list.
