### ISSUE TITLE
Project Level 5_4 Problems

### ISSUE THREAD

**Issue by DanielSjtea** [nus-cs2030/2021-s2#204]
# Summary
My current implementation manages to pass till Test Case 5_4, and upon further inspection, I'm finding out that my PriorityQueue of events is not polling the lowest time event when the number of customers is too high (around >95). Honestly not sure why this happens as it works perfectly well until the number of customers is increased to a very high amount.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/48090659/114300740-5c874a00-9af4-11eb-890b-5f9761799759.png)

**Comment by seancxy** [comment]
Hi Daniel, it should be fine if you're using java's PriorityQueue API, do check your comparator / comparable if you think the polling order is not right. 
It could be something else causing this problem like the event times of 'rescheduled' serve events from server rest or wrong service times of the customers (service time to be generated only at serve events)

**Comment by chengseong** [comment]
It seems like your customers are arriving out of order , so it could be due to your implementation somehow generating events again even after they have already been processed, so you might want to check that out
