### ISSUE TITLE
Query on Submissions

### ISSUE THREAD

**Issue by e0543978** [nus-cs2030/2021-s2#207]
# Summary

I'm uncertain about whether I have to submit my code on the main Lab 6 submission page.

## Description:

Given that each Task in Lab 6 has its own submission page, I was wondering if another submission is required on the main Lab 6 submission page. Thank you!

**Comment by gableejh** [comment]
Nope, you just have to submit it to the respective pages. Main one not needed

**Comment by brendancjz** [comment]
Yup, just submit on the individual problems!

**Comment by SrinivasG99** [comment]
Individual problems will suffice. Don't have to submit for main one.

**Comment by dumbasssoul** [comment]
yep the main one is just to display the questions i guess

**Comment by e0543978** [comment]
Awesome, thanks for your help everyone!
