### ISSUE TITLE
More Generic Invariance / Covariance (Related to PA2)

### ISSUE THREAD

**Issue by haveneshb15** [nus-cs2030/2021-s2#208]
PA2 has this line:

> ...counting is a form of aggregation, make Count a sub-class of Aggregate.

So I tried.

```
class Count<T> extends Aggregate<S, T> {
...
}

```
This will cause a compile-time error 

` error: cannot find symbol`

since type S is not included in Count<T>.

Hence, is it possible for any subclass to inherit only one generic type from a superclass with two generic types? Or did I misunderstand the question completely?

**Comment by OuaisBien** [comment]
maybe replace S with `Integer`?

**Comment by brendancjz** [comment]
Yup, replace S with Integer. This is because Count is a specific form of Aggregate so we know for sure that S will be Integer.

**Comment by amoscookeh** [comment]
You could do Aggregate<T,T> so that Count<T> inherits an Aggregate with only T generic types. However, this would not be useful in this case since we know for a fact that the seed will be an Integer for Count. Thus, as brendanczj has mentioned, we can extend an Aggregate with S fixed as an Integer.

**Comment by haveneshb15** [comment]
Thank you everyone for your input! 👍
