### ISSUE TITLE
Project level 3 test case3_3

### ISSUE THREAD

**Issue by yaohua98** [nus-cs2030/2021-s2#212]
# Summary
Not sure if anyone experienced the same error but the sequence of two events is wrong here (same time but the one with higher customer ID is polled out first), even though I dont think theres anything wrong with my eventcomparator

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/78200689/114644961-1a842100-9d0b-11eb-98fb-16dc57499794.png)
![image](https://user-images.githubusercontent.com/78200689/114645028-3edffd80-9d0b-11eb-959d-e88540260883.png)

**Comment by kexinnnwang** [comment]
Hi I think you can refer to #153 where someone raised a similar issue.  You should use Math.abs(e1.getTime() - e2.getTime()) < 10e-15 when testting time equality instead of e1.getTime() == e2.getTime().

**Comment by yaohua98** [comment]
> Hi I think you can refer to #153 where someone raised a similar issue. You should use Math.abs(e1.getTime() - e2.getTime()) < 10e-15 when testing time equality instead of e1.getTime() == e2.getTime().

OHHH ICICI thankyou so much!!

**Comment by karintang** [comment]
Doing addition and subtraction too many times might incur a slight difference in decimal points.
