### ISSUE TITLE
PA2 error

### ISSUE THREAD

**Issue by yaohua98** [nus-cs2030/2021-s2#217]
After adding the overloaded map method which takes in Function<S,Pair<S,T>> function only, I got these errors when running the test cases. I'm only at level 3 currently, but I still somehow get the output. Any idea why?
![image](https://user-images.githubusercontent.com/78200689/114719948-27842d00-9d6a-11eb-8c9b-22d132d02c81.png)

**Comment by peguin40** [comment]
instead of doing `jshell -q *.java < test1.jsh` , try to do `jshell -q your_java_files_in_bottom-up_dependency_order < test1.jsh` ie `jshell -q Circle.java Aggregate.java Count.java < test1.jsh`

**Comment by chooweixiang98** [comment]
I had this issue too. In my case, the issue was due to the order in which the files are opened in jshell.

**Comment by mltnsia** [comment]
Ensure the order of your files is appropriate based on dependency.

**Comment by chamath2030** [comment]
instead of using * type out the order one by one

lastly, huge shoutout to my githubber @OuaisBien

**Comment by Atem729** [comment]
Ensure bottom-up dependency order when opening files to test with jshell, there would be an issue for instance opening Count.java before Aggregate.java as Count would have no Aggregate to inherit from

**Comment by ARPspoofing** [comment]
You should open Circle followed by Pair followed by Aggregate followed by Count. Circle and Pair can be swapped but make sure Aggregate is opened before Count.

**Comment by oliverguicw** [comment]
Hi you would need to ensure that your files are opened in bottom-up dependency order. So you should open Circle and Pair first (order for this does not matter), followed by Aggregate and then followed by Count as Count extends Aggregate.

**Comment by i-sack** [comment]
Hi, I recommend that you open your java files one by one through typing them individually and not using a wildcard import. The sequence in which you type should be from the least dependent to the most dependent too!

**Comment by jeromesjj08** [comment]
Hi, I had the same issue also. I had to retype all my codes from scratch and then ignoring the issue vim is showing me, I just uploaded to codecrunch and it still passed the testcases. I still have the error on vim if I do a jshell *.java, but nothing on codecrunch. 
Hope this helps=)

**Comment by keithcharlesc** [comment]
The issue is most likely due to the order of the files since it has to be based on dependency order, manually typing them out based on the sequence should work!
