### ISSUE TITLE
pa2 test2.jsh

### ISSUE THREAD

**Issue by dumbasssoul** [nus-cs2030/2021-s2#218]
im not sure why my code doesnt give any output for the last test case in test2.jsh
<img width="822" alt="Screenshot 2021-04-14 at 11 16 40 PM" src="https://user-images.githubusercontent.com/78250616/114735141-7a181600-9d77-11eb-8dea-aa0af1e50bef.png">

my S and T values are correctly printed so im not sure where the problem lies

![image](https://user-images.githubusercontent.com/78250616/114736081-602b0300-9d78-11eb-83fc-6b2c107d5798.png)

**Comment by hewtungyuen** [comment]
by any chance did you use String.format()? the last test case requires the use of a double instead of an integer. thus, using %d representing integer in String.format() would be wrong and hence there would be no output.

**Comment by marvinljw** [comment]
Yes I agree with tung yuen here. Perhaps you should change it to a more general output? like %s?

**Comment by dumbasssoul** [comment]
thanks @hewtungyuen @marvinljw ! got it to work :)

**Comment by radellng** [comment]
@dumbasssoul I think what tung yuen and marvin said is true. Having a more general typing like '%s' will be useful in solving your problem.

**Comment by dumbasssoul** [comment]
> @dumbasssoul I think what tung yuen and marvin said is true. Having a more general typing like '%s' will be useful in solving your problem.

yep i did that, thanks!
