### ISSUE TITLE
Project Test Case 4_3 Output

### ISSUE THREAD

**Issue by hypernuggets** [nus-cs2030/2021-s2#222]
![image](https://user-images.githubusercontent.com/64246684/114897031-718d1180-9e43-11eb-8d21-e01f461c8fd0.png)

Hi, I'm getting this issue with my output in test case 4_3. Does anyone have any idea how to solve this?

**Comment by yuyitan** [comment]
A server that is resting can still accept waiting customers. Also check that you update your server correctly after they finishing serving a customer so that it frees up a slot in their queue.

**Comment by hypernuggets** [comment]
Managed to solve it with that hint, thanks!
