### ISSUE TITLE
[Project Level 5] Issues with customer service time and server rest

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#228]
I managed to pass the first 2 given sample cases of Level 5. However, once server rest comes into play, the rescheduling of pre-scheduled serveEvents completely throws my simulation apart as the customer service time is not fixed, and is only generated when a serveEvent occurs. This means that previous service time generated for my customer will not be valid if the server in-charge happens to rest midway. If I cannot reschedule events as it will throw the random seed pattern off, what way can I better handle random customer service time with server rest?

Currently, how I generate the customer's service time is by using a Supplier in my Customer class.  It looks like this:
```
double getServiceTime() {
        return (this.hasBeenServed == true || this.serviceTime != -1.0) ? this.serviceTime : serviceTimeSupplier.get();
    }
```
Would appreciate any tips or advice on how to solve this level! Thanks :'')

**Comment by seancxy** [comment]
Hi yuyi, you might want to save the service time in a class attribute. In your case, once a customer has a service time value, it doesn't need to generate another service time.

**Comment by Deshun99** [comment]
hi @yuyitan yuyi, maybe u might want to change the server time into a Supplier<Double>  since the nth customer to arrive might not be the nth customer to be served

**Comment by marcuslim835** [comment]
hi I believe it is possible to pregenerate all the service time and append them all into an arraylist and pass the arraylist into your method serveEvent, in which the method pops the first value out.

**Comment by yuyitan** [comment]
> hi I believe it is possible to pregenerate all the service time and append them all into an arraylist and pass the arraylist into your method serveEvent, in which the method pops the first value out.

Hi, did you manage to pass the hidden test cases (especially those lengthy ones) on Codecrunch with this method? Thanks!

**Comment by marcuslim835** [comment]
> > hi I believe it is possible to pregenerate all the service time and append them all into an arraylist and pass the arraylist into your method serveEvent, in which the method pops the first value out.
> 
> Hi, did you manage to pass the hidden test cases (especially those lengthy ones) on Codecrunch with this method? Thanks!

yup ive managed to clear all 5 levels!

**Comment by elitanzc** [comment]
> I managed to pass the first 2 given sample cases of Level 5. However, once server rest comes into play, the rescheduling of pre-scheduled serveEvents completely throws my simulation apart as the customer service time is not fixed, and is only generated when a serveEvent occurs. This means that previous service time generated for my customer will not be valid if the server in-charge happens to rest midway. If I cannot reschedule events as it will throw the random seed pattern off, what way can I better handle random customer service time with server rest?
> 
> Currently, how I generate the customer's service time is by using a Supplier in my Customer class. It looks like this:
> 
> ```
> double getServiceTime() {
>         return (this.hasBeenServed == true || this.serviceTime != -1.0) ? this.serviceTime : serviceTimeSupplier.get();
>     }
> ```
> 
> Would appreciate any tips or advice on how to solve this level! Thanks :'')

Hi, i think that rescheduling events shouldn’t affect the random seed pattern if the service time is only generated when the serveEvent is processed. The way i solved it without generating the service times before serveEvent is processed was to schedule the serveEvent when processing waitEvent only if the queue is empty, and always schedule the serveEvent for the immediately next customer in queue whenever a serveEvent is being processed.
