### ISSUE TITLE
Checkstyle - WhitespaceAround Issue

### ISSUE THREAD

**Issue by keithcharlesc** [nus-cs2030/2021-s2#23]
Encountered this issue **WhitespaceAround** while using checkstyle and not too sure what it means exactly:

<img width="927" alt="Screenshot 2021-02-04 at 4 34 04 PM" src="https://user-images.githubusercontent.com/75473030/106865929-ce16d680-6706-11eb-900c-95a79745a51c.png">

Does anyone know what it means or a way around it? Thank you!

**Comment by kexinnnwang** [comment]
There should be a white space before and after binary operators eg it should be a * b; instead of a*b; and a / b; instead of a/b;
You can check https://www.comp.nus.edu.sg/~cs2030/style/ for style guide

**Comment by dumbasssoul** [comment]
also, for the first issue, you missed out a space between your "if" and the following condition!

**Comment by miao-tianjia** [comment]
Generally, this WhiteSpaceAround issue occurs when you do not follow the format for spaces required (by CS2030). This means that you are missing/putting space inappropriately before/after the operator or command mentioned in the comment given, so simply follow what the comment says!

**Comment by keithcharlesc** [comment]
Managed to fix it, thanks a lot everyone!
