### ISSUE TITLE
How queuing works with rests now-Project level 4_3 

### ISSUE THREAD

**Issue by KaveenE** [nus-cs2030/2021-s2#231]
# Summary
Codecrunch test case 4.3 wrong output

## Description 
I'm guessing the output is wrong due to 2 possible reasons:
1) My understanding of how the queuing works with rest is wrong
2) or i did not implement rests properly(less likely)

Based on the test case kindly provided by @brendancjz here: https://github.com/nus-cs2030/2021-s2/issues/205#issuecomment-817728770, my waiting aspect should be correct.

It was difficult for me to understand the discussion here on how the queuing works with rest here: https://github.com/nus-cs2030/2021-s2/issues/202#issue-855127157.

This is my understanding from that discussion:
```
//Get the 1st non-resting server that doesn't have any customers
//Else get the first non-resting server that can at least 
//accommodate into their queue(for greedy customers, we want the smallest queue)

//If at this point, we haven't gotten a server yet. 
//We repeat the same steps mentioned above 
//BUT we don't care if they are resting or not (ie Project Level 3 logic)
```
Can someone clarify if my understanding is correct and provide some possible reasons to why 4_3 isn't working?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/59110376/115098006-169d0c80-9f60-11eb-8c4f-ac06f172e263.png)

**Comment by eryuanren** [comment]
Hi! I had the same issue... but I realized it is due to how your program sorts the arrive customers to the servers. You can see my comment here for more info!

https://github.com/nus-cs2030/2021-s2/issues/230#issuecomment-821753070

**Comment by brendancjz** [comment]
Hi there, I'm glad my test case helped you in some way. For my queuing implementation, my logic is this:
First, i loop through the entire Server array/ArrayList to find a server that is currently not serving AND not resting. This will lead to the ServeEvent.
Second, if that first loop does not work out, I will get the first Server that is not fully occupied but this is after I sorted the Servers in the array/ArrayList in a Priority Queue. The sorting is based on who has the lower size and then followed by who has the smaller ID. Hope this helps.

**Comment by KaveenE** [comment]
Hello there, looks like both your ideas are the same:
(1)Check for a server that's not resting & no customers(ie 0 customers in queue & not serving anyone)
(2)If that fails, check for a server who has the least queue size(regardless if he resting). Break ties by who has the least id.

But it seems to be step (2) is meant for only `greedy` customers since in (2) we not only want a server who can accommodate them into the queue but also has the least queue. Do we not distinguish between `greedy `and `normies `?

**Comment by eryuanren** [comment]
@KaveenE  oop yes sorry! that is for greedy! so for normies they just look if they have space. and like previously said, the space is dictated by how many people are waiting

**Comment by KaveenE** [comment]
Ahh, thanks guys, appreciate the speedy response, it got through!

For anyone looking for a TLDR, just follow this:
(1)Check for a server that's not resting & no customers(ie 0 customers in queue & not serving anyone)

(2i)If (1) fails and we have a `greedy `customer, check for a server who has the least queue size(regardless if he resting). Break ties by who has the least id.
(2ii)If (1) fails and we have a `normie`, just check for a server who can accommodate us. Break ties by who has the least id.
