### ISSUE TITLE
cant pass test case 3

### ISSUE THREAD

**Issue by davidwang98** [nus-cs2030/2021-s2#234]
# Summary

So I'm able to pass the levels on the codecrunch but when i submit it shows this error

## Description:

I dont see any of this code in my Main.java

## Code Snippets

nil

## Screenshots

![image](https://user-images.githubusercontent.com/71161461/115110149-80db9e80-9fac-11eb-8e6b-a9c7ed7d07b8.png)

**Comment by marcuslim835** [comment]
maybe try .join() after .thenCompose instead of inside .thenCompose?

**Comment by davidwang98** [comment]
> maybe try .join() after .thenCompose instead of inside .thenCompose?

my Main.java does not have that code so am not sure where this routes thing even came about.

![image](https://user-images.githubusercontent.com/71161461/115117587-f27a1380-9fd1-11eb-893f-957bd25f8403.png)
