### ISSUE TITLE
return types for level3

### ISSUE THREAD

**Issue by marcuslim835** [nus-cs2030/2021-s2#236]
# Summary
"BusRoutes cannot be converted to CompletableFuture". Why cant I just return the bus routes though?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots
![image](https://user-images.githubusercontent.com/77620616/115112937-555fb080-9fba-11eb-813e-3f4c79026cdc.png)

**Comment by e0560113** [comment]
i think the map in busroutes should be of type Map<BusService,CompletableFuture<Set<BusStop>>>

**Comment by marcuslim835** [comment]
oh icic i might have overcomplicated things by returning CompletableFuture<Map<BusService,CompletableFuture<Set>>>
