### ISSUE TITLE
Project 5_12 Error

### ISSUE THREAD

**Issue by KaveenE** [nus-cs2030/2021-s2#240]
# Summary
Put a summary of the question

## Description 
This case tests you on the queuing logic for greedy customers and my queuing logic for greedy customers is based on this:https://github.com/nus-cs2030/2021-s2/issues/230#issuecomment-821804627.

I'm positive my queuing logic should be correct considering that I use a PQ and then poll to get the Server I want.

At first, my server id was wrong then my customer id was wrong as shown in the picture below.

I really don't know where is the bug in my queuing logic.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/59110376/115118632-b7c6aa00-9fd6-11eb-850e-a1a35987111d.png)
![image](https://user-images.githubusercontent.com/59110376/115118675-f6f4fb00-9fd6-11eb-9a50-2780f64d6430.png)
![image](https://user-images.githubusercontent.com/59110376/115118634-bbf2c780-9fd6-11eb-86b7-947f55037c6d.png)

**Comment by isaactyj** [comment]
@KaveenE Hello, may i know how u solved it? I am currently facing the same issue not sure why my customer 20(normie) does not recognize server 1 as full

**Comment by KaveenE** [comment]
Hi sorry for the late reply, I actually didn't finish it. I'll probably will try it again some other time before the deadline though(hopefully)
