### ISSUE TITLE
Help with RandomGenerator

### ISSUE THREAD

**Issue by chengseong** [nus-cs2030/2021-s2#241]
I cannot figure out how to compile all my classes into the cs2030/simulator package. I have included `package cs2030.simulator` to the top of all my java classes and then ran `javac -d *.java`, but i get the error `javac : not a directory: Arrive.java`. Really appreciate any help!

**Comment by chengseong** [comment]
Also for some reason I cant assign a label to the issue D:

**Comment by elitanzc** [comment]
> I cannot figure out how to compile all my classes into the cs2030/simulator package. I have included `package cs2030.simulator` to the top of all my java classes and then ran `javac -d *.java`, but i get the error `javac : not a directory: Arrive.java`. Really appreciate any help!

You can run `javac -d .  *.java` instead
