### ISSUE TITLE
Project Level 5 

### ISSUE THREAD

**Issue by rendao1010** [nus-cs2030/2021-s2#242]
# Summary
I'm trying to start on Level 5, but looking at some of the previous threads there was some mention of including `package cs2030.simulator` at the top of every file, then executing `javac -d . *.java`. However, this is the error message that I got. Does anyone know how I can get around to solving this issue? Thanks! 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/64304450/115120621-04af7e00-9fe1-11eb-971b-e40ccb80f71f.png)

**Comment by cjunhong99** [comment]
Hi rendao! I notice that you are compiling your code in the current directory which contains all your .java files. 
Assuming that you have `package cs2030.simulator` at the top of every file (except your Main files of course), this would not work as from what I know the compiler will try to search for the 'CS2030' directory in your 'project5' directory which doesn't exist.
What you can try is to navigate out into the directory that contains 'CS2030' (/home/rendao1010) and do
`javac CS2030/project5/*.java`
This seemed to have worked for me on mac and I have attached a screenshot for reference.
![Screenshot 2021-04-18 at 2 11 47 AM](https://user-images.githubusercontent.com/77767883/115122757-324df480-9fec-11eb-8bc1-1a5a1133de11.png)

**Comment by rendao1010** [comment]
Hi junhong, thanks for your help! I tried the above but still ran into the same issue, unfortunately :(

**Comment by cjunhong99** [comment]
Hi so sorry I just realised after reading your post again that you probably need to place all your .java files (besides ur Main files) into the directory 'cs2030/simulator' (which should contain RandomGenerator.class) as using `package cs2030.simulator` probably means that the compiler will read your files from that directory. (So maybe add that directory into your 'project5' directory)
After doing so, compiling with `javac cs2030/simulator/*.java` should work (hopefully)

**Comment by Pchrome** [comment]
Hi maybe you want to to re-shuffle your files this way instead If it isn't done so already.
1. In your working directory put all your .java files there.
2. Then in the same working directory create your cs2030/simulator subdirectory
3. There you will put the rng class file
4. For each java file (excluding main java files), for e.g Event.java, at the very top of the file, declare package cs2030.simulator;
(So when u compile, all your class files will be added into the cs2030/simulator sub directory)

5. Inside your main files, you will instead import each class file with import cs2030.simulator.(name of class file)

**Comment by rendao1010** [comment]
Thank you all! Just to check, must the classes and/or methods in your other files all declared public as well?

**Comment by yuyitan** [comment]
As Main classes are not part of your package, you will have to make any class that you need to import into the respective Main classes public, with public constructors as well. Basically, anything from the package that you need to use in your Main classes have to be public and imported at the top.

**Comment by rendao1010** [comment]
Thank you all for the help! I have successfully solved the issue with the suggestions above, in case anyone runs into a similar problem in the future.
