### ISSUE TITLE
Stream.reduce

### ISSUE THREAD

**Issue by changjianxiang** [nus-cs2030/2021-s2#243]
Hi, I can't seem to figure out how to do the part e of the following question. Does anyone have any clue?

![image](https://user-images.githubusercontent.com/77479126/115137185-2d725a80-a057-11eb-8c93-071a03a36489.png)
![image](https://user-images.githubusercontent.com/77479126/115137190-36632c00-a057-11eb-9375-38e1847a8802.png)

For part d, I did the following and it seems to be right. But for part e:
![image](https://user-images.githubusercontent.com/77479126/115137207-4aa72900-a057-11eb-872e-01dbd80e0e5b.png)
![image](https://user-images.githubusercontent.com/77479126/115137217-5561be00-a057-11eb-96c3-5ccc0979628e.png)

I attempted to do it this way but it is wrong... Does anyone know how I can do the question part e? where I only utilises 1 reduce function? Thanks in advance!

**Comment by yuyitan** [comment]
What about .reduce(0, (x,y) -> x.length() + y.length()) ?

**Comment by changjianxiang** [comment]
![image](https://user-images.githubusercontent.com/77479126/115139244-5b5d9c00-a063-11eb-96ef-e6c2012ad56a.png)

It still doesn't work :"(

**Comment by KaveenE** [comment]
Try this:
`words.stream().reduce(0, (x, y) -> x + y.length(), ( x, y) -> x + y);`

**Comment by changjianxiang** [comment]
Nice it worked! Thanks alot for the help!!!
