### ISSUE TITLE
Project Grading

### ISSUE THREAD

**Issue by tyc001** [nus-cs2030/2021-s2#248]
Hi, fairly minor question here: Is the project graded purely on correctness w.r.t the test cases in CodeCrunch or is some part of the grading based on style and structure? Professor Henry's latest email regarding the addition of a final level which performs 'style checking, as well as appropriate packaging' seems to imply that there is some possibility of the latter? Thanks!

**Comment by OuaisBien** [comment]
I think you can expect pretty much the same thing as normal lab tasks (indent, 100 per line ...) plus all the packaging on Codecrunch. If you nail all the test cases, style checking and appropriate packaging, you get an A (100/100). Not sure if that translate to 10/100 of the final grade tho.

**Comment by gableejh** [comment]
you should get full marks so long as you pass all the test cases

**Comment by tyc001** [comment]
Alright, thanks!
