### ISSUE TITLE
Time Limit Exceed Error Level 5_4

### ISSUE THREAD

**Issue by KingRyo13** [nus-cs2030/2021-s2#250]
# Summary
Somehow I managed to pass all previous test cases until this one where I start getting wrong allocations and a time limit exceeded flag. For this level I passed the randomGenerator to my Arrive event which then passes it on to my Wait or Serve event.
Does anyone know why possibly? Could it be due to rescheduling? Every time my Serve event finds that the Server is idle or resting, it reschedules with the next time the server is next free. There shouldn't be a problem right?

## Screenshots (if any): 
Errors:
![image](https://user-images.githubusercontent.com/77270665/115158319-1ca9ff00-a0c0-11eb-8f8e-4975f73b15ec.png)

Below is my Serve event so yall can see the structure. WaitStaff is my class containing the array of Servers:
![image](https://user-images.githubusercontent.com/77270665/115158354-5418ab80-a0c0-11eb-8781-d151b746c706.png)

Thanks!

**Comment by yuyitan** [comment]
I too had some rescheduling in my Level 4, but as I was doing Level 5, I realised that will throw the seed pattern off so I got rid of it. For Level 5, instead of rescheduling, I only schedule serveEvents from waitEvents if there is no server rest (aka restProb is 0). For the rest of the waitEvents, I will schedule the next waiting customer in queue when processing my serveEvents, as well as when any serverBackEvent is triggered (when server comes back from rest).

**Comment by KingRyo13** [comment]
> I too had some rescheduling in my Level 4, but as I was doing Level 5, I realised that will throw the seed pattern off so I got rid of it. For Level 5, instead of rescheduling, I only schedule serveEvents from waitEvents if there is no server rest (aka restProb is 0). For the rest of the waitEvents, I will schedule the next waiting customer in queue when processing my serveEvents, as well as when any serverBackEvent is triggered (when server comes back from rest). Also ensure that you only call to get the customerServiceTime at one point (only when processing serveEvents).

I found out my issue was because my rescheduling reschedules a Serve event to the "nextDoneTime" of that particular Server if the Server is busy or resting. The problem is that I update this "nextDoneTime" variable ever time a Done event is triggered, so an unlimited number of Serve events will be rescheduled to the same specific time, causing a time limit error.

I think I'll modify my Events to be something like yours, thanks for the tip!
