### ISSUE TITLE
Project cyclic dependencies

### ISSUE THREAD

**Issue by KingRyo13** [nus-cs2030/2021-s2#258]
# Summary
My code runs in jshell but fails CodeCrunch because of this.

## Description 
Due to time limit issues passing level5_4 as I was rescheduling Serve events to donetimes that are not updated yet (as donetimes are only updated in the Done event due to rest times), I deleted my old Event classes and made new ones.

Previously it was Arrive -> Wait -> Serve -> Serve (for reschedule if needed) -> Done
Now its Arrive -> (if server is busy, add the customer to queue) -> Serve -> Done -> Serve (if queue contains more customers) -> End

Here there are cyclic dependencies between Done and Serve, EVEN THOUGH a Done will only return a Serve IF the queue is not empty, otherwise, it will return End, so there's no way that Done and Serve will infinitely return each other.

Does anyone know how I can get around this? I tried doing it in the main class (by having Done pass on customer details to End, which contains a method that returns a Serve), but the cyclic dependencies still happened.
## Screenshots (if any): 
Main next event:
![image](https://user-images.githubusercontent.com/77270665/115246095-297a3180-a158-11eb-8f23-3084d89b2fc3.png)

**Comment by ireneliee** [comment]
My TA suggest me to not let the event class handle other event class directly, but make the types of event a shared property between classes, and then hve them return the type to let another class handle it.

The example he gave me was that arrive class should know that wait is a type of event (use enum in super class) ,but not directly handle the wait class,instead passing the details off for another class to handle it.
