### ISSUE TITLE
compilation error on codecrunch

### ISSUE THREAD

**Issue by dumbasssoul** [nus-cs2030/2021-s2#26]
I tested out everything on vim and it works fine, but when I submit it on codecrunch the test output shows:

field arrivalTime in class Cruise
field cruise in class Loader
field identifier in class Cruise
field identifier in class Loader
not declared private final
Grading terminated.

Does it mean I cant use "protected final" in my code? Is the solution to that just creating a public get method for these attributes?

**Comment by Yung-Jer** [comment]
Yes, you should declare all the attributes as private final instead of protected final.

**Comment by gableejh** [comment]
You'll have to declare the variables are private final, then perhaps you can use a protected get method to pull out these attributes (might violate the tell don't ask principle).

**Comment by dumbasssoul** [comment]
okay thanks all for the help!
