### ISSUE TITLE
Project Test Case 5_9

### ISSUE THREAD

**Issue by JiaJun98** [nus-cs2030/2021-s2#262]
# Summary
Unable to pass this test case

## Description 
Apparently, according to the screenshot. It looks like the customers are non-greedy with 2 servers and a maximum of 1 queue each. Seems like my rest was not implemented correctly. Not sure where did I go wrong in this case...

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/59722769/115284188-f26b4680-a17e-11eb-8b18-abbb5d4ee9fc.png)

**Comment by hypernuggets** [comment]
You might want to check how you're getting the next start time for the next service? It looks like your code is taking the done time of the other server as the start time of the next customer after the server finishes resting, instead of taking the rest time from the generated rest timings and adding that time to the customer waiting in the queue.

**Comment by RachelCheah** [comment]
hi, I think we need more information about how you generated your events/how you incorporated the rest times to help you out !!

**Comment by JiaJun98** [comment]
@RachelCheah @hypernuggets 
Thank you for your help. I managed to solve that bug but I am now at the last part of this test case.
For generating my event, I initally put them using an ArriveEvent with the server inside the ArriveEvent.
When resting, (I generate the restTime right when the server is done serving the customer), I input an restEvent which will cause the server to serve if there is a customer which then triggers it to put the DoneEvent.

![image](https://user-images.githubusercontent.com/59722769/115443116-725be400-a245-11eb-9206-ac864e0c51f9.png)


Thank you for your help once again

**Comment by JiaJun98** [comment]
Thank you I have settled it
