### ISSUE TITLE
Test Case 5_4 Wrong Customer Type

### ISSUE THREAD

**Issue by mickJirapat** [nus-cs2030/2021-s2#263]
I'm not sure why my generator is producing the wrong type of customers. Currently, I'm producing a new Customer (and running generator.genCustomerType()) when adding a new ArrivalEvent to the PQ. I also tried a different approach by generating all the customers at the very beginning and store them in an ArrayList, which resulted in the same errors. Anyone else got the same problem?
![Error 1](https://user-images.githubusercontent.com/75828969/115333571-7ac40880-a1cc-11eb-83c4-a019642d9fc9.png)
![Error 2](https://user-images.githubusercontent.com/75828969/115333574-7bf53580-a1cc-11eb-98cc-fc4d48ab5df6.png)

**Comment by OuaisBien** [comment]
I don't think its about how you generating the type of customer because the customer type is indeed correct in the arrive event. You are just missing the `(greedy)` string, so maybe it has something to do with the how the customers are store or how you make sure the customer is greedy or not....

**Comment by mickJirapat** [comment]
Lol I just realized that the problem only happens with the leave event and went back to fix the toString method in there. Thanks @OuaisBien !
