### ISSUE TITLE
Project 5_3 - Server in my code is resting, but in CodeCrunch, Server is serving

### ISSUE THREAD

**Issue by chxnhxng** [nus-cs2030/2021-s2#275]
Hello! My output for 5_3 is on the right, and CodeCrunch's on the left. 

My Server 2 was granted a 2.7547 unit time break session, so the server will start working at 4.659. Hence when Customer 4 arrived, server 1 was tasked to serve. But on the left, it seemed like server 2 did not take a break - when Customer 4 arrived, server 2 was the one serving. 

I use `.genRandomRest()` when an event of DONE is being polled, then followed by `.genRestPeriod()` if `.genRandomRest()` gives a value lower than `the probability of resting, Pr`. 

May I know what could've gone wrong? Thanks in advance! :)

<img width="702" alt="Screenshot 2021-04-21 at 3 15 46 AM" src="https://user-images.githubusercontent.com/65957285/115451512-de434a00-a24f-11eb-8263-a455dff9727d.png">

**Comment by OuaisBien** [comment]
looks like you are generating the wrong length of rest. Maybe some problems about RandomGenerator itself or `.genRestPeriod()` and `.genRandomRest()`?

**Comment by chxnhxng** [comment]
> looks like you are generating the wrong length of rest. Maybe some problems about RandomGenerator itself or `.genRestPeriod()` and `.genRandomRest()`?

Thanks for your comment omg! I realise I forgot to remove a chunk of code that used `.genRandomRest()` from a previous idea!
