### ISSUE TITLE
Lab 8 level 2 not sure what these errors mean

### ISSUE THREAD

**Issue by KingRyo13** [nus-cs2030/2021-s2#276]
# Summary

I'm really confused with what is supposed to be done here in the `getBusStops` method.

![image](https://user-images.githubusercontent.com/77270665/115463478-6fb9b880-a25e-11eb-8253-c4595d672541.png)

 Codecrunch says take note of the compilation errors, which is because Scanner cannot take in a CompletableFuture. I'm assuming I have to flatMap (thenCompose) it or something to get out the String but it doesn't work and honestly idk.

![image](https://user-images.githubusercontent.com/77270665/115463090-ffab3280-a25d-11eb-93bf-0d45744f92ff.png)

## Screenshots
![image](https://user-images.githubusercontent.com/77270665/115463139-0c2f8b00-a25e-11eb-9173-a07ac22405a8.png)

Can someone explain how I should modify the scanner to work with CompletableFuture?

And how I should modify `findStopWith` after that?

Thanks!

**Comment by kaiwenyay** [comment]
you cant pass a CompletableFuture into a scanner, so what i did was to have the scanner do its job within the CompletableFuture instead. the method should now return a CompletableFuture.

**Comment by chelleadel** [comment]
The Scanner cannot read a ComparableFuture, so it is an error.
So you will have to wrap the Scanner around the ComparableFuture and pass the String within BusAPI.getBusStopServedBy(serviceId).

**Comment by liongthryan** [comment]
I ran into the same issue, but to try to fix it I also wrapped the Scanner around the ComparableFuture. Hope your code works soon.

**Comment by jj-jenny** [comment]
Scanner cannot take in a CompletableFuture. You can make use of .thenApply and lambda (similar to level 1) and then continue with the Scanner function inside the .thenApply.
- For example, .thenApply(stop -> {Scanner sc = new Scanner(stop).......});

findStopsWith can make use of .thenApply() as well.

**Comment by elizabethh07** [comment]
wrap Scanner in CompletableFuture eg. CompletableFuture<Scanner> sc = BusAPI.getBusStopsServedBy(serviceId)
after that i use thenApply and thenAccept at the end

**Comment by elizabethh07** [comment]
For findStopsWith method, i use thenApply eg. _.thenApply(x -> x.stream())_

**Comment by KingRyo13** [comment]
Thanks all for the help. Something I'm doing is still not right though.
Rn I changed the method to return a CompletableFuture of the Set. What wrong with this?:

![image](https://user-images.githubusercontent.com/77270665/115571181-56ae1780-a2f1-11eb-8db3-3537e14c6c0e.png)
