### ISSUE TITLE
Project Level 4 Hidden Test Case

### ISSUE THREAD

**Issue by sarahjingwen** [nus-cs2030/2021-s2#283]
# Summary
Failing test case 4_3

## Description 
Hello Im really confused why my customer 13 keeps leaving and why 16 is waiting at server 2 instead? 
I found the hidden test case in #238 and I tried to print out the rest times and when the server is resting and done resting. Am I reading the rest times correctly? 
Also I was wondering can customers still queue at a resting server?

## Screenshots (if any): 
<img width="449" alt="2021-04-21 (2)" src="https://user-images.githubusercontent.com/71871458/115521049-56942480-a2bd-11eb-82fd-ebe04e697460.png">
<img width="277" alt="2021-04-21 (4)" src="https://user-images.githubusercontent.com/71871458/115521532-d4583000-a2bd-11eb-9b98-0113171b2ce3.png">
<img width="280" alt="2021-04-21 (5)" src="https://user-images.githubusercontent.com/71871458/115521605-e4700f80-a2bd-11eb-9792-224603cb96df.png">

**Comment by Pchrome** [comment]
Hi, the customers won't be served but they still can be queued at resting servers as long as there is space available.

**Comment by foosh123** [comment]
Hi, the customer still can join the waiting queue even if your server is resting, so it might the logic of ArriveEvent to WaitEvent that is causing this error. Hope this helps!

**Comment by keithcharlesc** [comment]
Customers can still queue even though the server is resting, would recommend checking the conditions on how customers are able to choose their server and also the server properties just to be safe

**Comment by sarahjingwen** [comment]
Ohh I didnt know customers could queue at a resting server haha.. I took away the check for resting server when the customer is selecting the queue and it works! Thanks so much!
