### ISSUE TITLE
Level 5 Private Test Case 5_8: Server serves 2 customers at the same time

### ISSUE THREAD

**Issue by chxnhxng** [nus-cs2030/2021-s2#284]
(i figured out! last photo is what i changed)
My server served 2 customers at one go, but I only poll 1 event from my Priority Queue at once, update all event times when the server goes to rest and once the customer being served has a service time. 

Any idea what could've been wrong? Thanks! Attached are the error and snippets.

## Screenshots
The error:
<img width="830" alt="Screenshot 2021-04-21 at 11 28 04 PM" src="https://user-images.githubusercontent.com/65957285/115580029-4d28ad80-a2f9-11eb-8734-de1ad8ac0073.png">

### **1. If the event is of type SERVE,** 
<img width="548" alt="Screenshot 2021-04-21 at 11 29 21 PM" src="https://user-images.githubusercontent.com/65957285/115580400-a1339200-a2f9-11eb-9960-09f67bbfe15d.png">

### **2. Event:: runServe   -- Update server availability, remove the customer from queue if he is in it, then return event of type DONE.**
<img width="659" alt="Screenshot 2021-04-21 at 11 29 49 PM" src="https://user-images.githubusercontent.com/65957285/115580391-9ed13800-a2f9-11eb-86ed-e96cbd00e7f8.png">

### **3. Updates all other customers in queue their SERVE event time**
<img width="724" alt="Screenshot 2021-04-21 at 11 30 10 PM" src="https://user-images.githubusercontent.com/65957285/115580384-9c6ede00-a2f9-11eb-97f2-d699f4654c6b.png">
<img width="561" alt="Screenshot 2021-04-21 at 11 30 21 PM" src="https://user-images.githubusercontent.com/65957285/115580363-9842c080-a2f9-11eb-90cc-a9c47bedf91e.png">

### updated for the 2nd last pic above
![image](https://user-images.githubusercontent.com/65957285/115589263-39357980-a302-11eb-8282-7ef3d286468e.png)

**Comment by chengseong** [comment]
Could it be due to how your Serve classes are being queued into the priority queue? Are your serve classes being created before your server goes on rest? In that case it is possible that your timings are all messed up due to that. Another possible problem could also be due to how your server checks whether it is possible to serve another customer based on the state it is in.

**Comment by jamesmakjxnp** [comment]
try creating a temporary function that prints out the server state after every event println so u can see what customer is being served and their serve time/rest time to know where the issue is. i found other bugs apart from the one i was trying to fix by doing this
