### ISSUE TITLE
Level 6 test case

### ISSUE THREAD

**Issue by ChristopherLiew** [nus-cs2030/2021-s2#288]
# Summary
Hi all, I've not been able to pass the level 6 test case for style and am not too sure what the issue is. For context, I've kinda separated out each level into its own set of classes that serve each of its respective MainX.java. 

So for level 5 and Main5.java for instance would have its own set of classes of Customer5, Server5, etc. I am not too sure if this might be the issue? Other than that I've done all the necessary javadoc commenting as well. Hope to get any advice on this! Thank you!

## Screenshots: 
<img width="1380" alt="Screen Shot 2021-04-21 at 17 54 14" src="https://user-images.githubusercontent.com/52255272/115534679-9ad9f180-a2ca-11eb-9b47-cf226d248b9c.png">

**Comment by yuyitan** [comment]
You should be using the same Customer, Server and Event etc for all your Main classes, with overloaded constructors when necessary. I'm not sure if that is what's causing the error though. Javadoc commenting is optional for the passing the checkstyles.

**Comment by chengseong** [comment]
It looks like there are too many classes and thats why the runtime for checkstyle is going on for too long.

**Comment by ChristopherLiew** [comment]
@yuyitan @chengseong Will try simplifying things! Thanks guys.

**Comment by ChristopherLiew** [comment]
Hey guys, I've cleaned up the classes as per @yuyitan advice but I'm getting this should not reside in the main directory error. Am I supposed to do some housekeeping with packages or something to separate the driver/ client classes from the other classes?

<img width="438" alt="Screen Shot 2021-04-22 at 02 38 56" src="https://user-images.githubusercontent.com/52255272/115604396-e5cc2700-a313-11eb-930f-4cec68942146.png">

**Comment by yuyitan** [comment]
Hi @ChristopherLiew, maybe you can show us how you organised your files?

**Comment by ChristopherLiew** [comment]
Hi @yuyitan here's how i organised my classes: 

Project 
|
+—cs2030
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+—MyRandomGenerator.java
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+—RandomGenerator.java
|
+—Customer.java
+—Server.java
+—Event.java
+—State.java
+—Stats.java
+—ManagementSystem1.java
+—ManagementSystem2.java
+—ManagementSystem3.java
+—ManagementSystem4.java
+—ManagementSystem5.java
+—Main1.java
+—Main2.java
+—Main3.java
+—Main4.java
+—Main5.java

Thx for the help!

**Comment by yuyitan** [comment]
Hi @ChristopherLiew , I think you're having the same issue as #294. All of your classes (except for Main classes) should have package cs2030.simulator; on top and should not be in the Main directory. Your Main classes should reside outside of the package and have the necessary classes imported individually on top. e.g. import cs2030.simulator.Server; etc. Hope this helps!

**Comment by ChristopherLiew** [comment]
I see, gotcha. That a lot @yuyitan !
