### ISSUE TITLE
Project: Using private static final (Level 2)

### ISSUE THREAD

**Issue by jeremyojf** [nus-cs2030/2021-s2#289]
# Initializing maxQueueLength
I was thinking of making the variable private static final, static since it's a constant throughout.

But I can't declare it in a constructor, since the constructor could be called more than once.

Any good ways of doing this? Or is it best to just use private final instead?

**Comment by Zekeseoj** [comment]
max queue length changes in most levels so i dont think its possible to define it as a constant. private final is how i did it.

**Comment by gableejh** [comment]
it's not always a fixed value so you should use private final

**Comment by ARPspoofing** [comment]
You should use private final because it will change. Also, it would be easier to keep track between event classes

**Comment by keithcharlesc** [comment]
Would be good to use private final as what the rest have mentioned

**Comment by Martini-Chwang** [comment]
Yepp private final has to be used cause CodeCrunch will flag it out

**Comment by jeremyojf** [comment]
Okay thanks for the replies! Was just wondering if it was possible.
