### ISSUE TITLE
How should I put constants in class constructors?

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2030/2021-s2#29]
# Summary

I use the code below for the constructor of the SmallCruise class. However, when I submit on CodeCrunch, I get a magic number warning: '30' is a magic number. I tried to declare new variables for these constants inside the class, but that leads to a compilation error: cannot reference (the variable) before supertype constructor has been called. Declaring the variables outside the class won't work either, because I get another warning on CodeCrunch: SmallCruise.java:1: error: class, interface, or enum expected.

I cannot figure out the correct way to put the constants into the class constructors. Can anyone help?

## Code Snippets

```
class SmallCruise extends Cruise {

    SmallCruise(String identifier, int arrivalTime) {
        super(identifier, arrivalTime, 1, 30);
    }
    ...
}
```

**Comment by Yung-Jer** [comment]
You can try declare as public static final int <var_name> = 30; then use the var to replace all the 30

**Comment by jethrokyq** [comment]
You can declare it as an attribute of SmallCruise like so:

``
private static final int CONST_NAME = 30;

``
The naming convention is typically all uppercase to differentiate constants from variables.

**Comment by miao-tianjia** [comment]
Define it as private static final <var_name> and replace all your constants with the var_name.
