### ISSUE TITLE
Level 5 packaging error 

### ISSUE THREAD

**Issue by jiahuitan36** [nus-cs2030/2021-s2#292]
Getting this error and some files are not being pacakaged into cs2030.simulator folder even though it has the 'package cs2030.simulator' at the top of those files. Eg. my WaitEvent and ServeEvent are not being packaged. 

![photo_2021-04-21_21-48-58](https://user-images.githubusercontent.com/60168038/115565714-316ada80-a2ec-11eb-8a2b-25c85d4b53fc.jpg)
![photo_2021-04-21_21-49-26](https://user-images.githubusercontent.com/60168038/115565721-33349e00-a2ec-11eb-8457-2082f4289845.jpg)

**Comment by jedkk** [comment]
the packaging command for all your non-main classes should not have "import" in them.
should be "package" instead

you only "import" a class only if you are using that class

**Comment by sarahjingwen** [comment]
I think the classes in the cs2030/simulator folder (eg. Event.java, ArriveEvent.java) should have "package cs2030.simulator;" at the top and I put the .java files in the cs2030/simulator folder as well.

The Main classes should have 
"import cs2030.simulator.Event;
import cs2030.simulator.WaitEvent;
...." 
at the top.

**Comment by jiahuitan36** [comment]
@jedkk ps write wrong LOL i used package cs2030.simulator!

**Comment by jedkk** [comment]
could be the way you import these classes from your Main files
