### ISSUE TITLE
PYP AY17/18 Sem1 Q14

### ISSUE THREAD

**Issue by gracefour11** [nus-cs2030/2021-s2#293]
# Summary
This is from AY17/18 Sem1 Q14
Does anybody know how to go about doing this? I don't really get what the question means by "Show how you would call **createSnippet** with the static method **shorten** from the class **TextShortener** as the strategy."

![image](https://user-images.githubusercontent.com/76483230/115578675-13a37280-a2f8-11eb-8cb3-e1d4bd396b73.png)

**Comment by jcng2308** [comment]
It just means how you would utilise the static method of TextShorter to execute void createSnipper(SummaryStrategy strategy)

So there are two possibilities. 
Using lambda
createSnippet((s,n) -> TextShortener.shorten(s, n));
or 
createSnippet(TextShortener::shorten);
