### ISSUE TITLE
Project Test Case 6

### ISSUE THREAD

**Issue by charmainechng** [nus-cs2030/2021-s2#294]
# Summary
Hello! I have ran into the error (as shown in the screenshot) and I am not sure what is causing it. More details would be that I have created a Driver class to help me import RandomGenerator for usage in IntelliJ (with reference to the solution brought up in issue #137 ). I am not sure if that is causing the problem :-( Thank you!

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/77719693/115585091-e954b380-a2fd-11eb-87b5-c17a60332287.png)

**Comment by isaactyj** [comment]
i think u created the classes inside of the main?

**Comment by Englishificational** [comment]
Those files aren't meant to be in the main directory. You could try moving those files to the cs2030/simulator folder with ```package cs2030.simulator``` added to the top and all your MainX files importing them.

**Comment by Atem729** [comment]
Your main files and your class files should not reside in the same directory

**Comment by charmainechng** [comment]
Thank you all for the help!
