### ISSUE TITLE
Special Sem PYP - Streams

### ISSUE THREAD

**Issue by chamath2030** [nus-cs2030/2021-s2#295]
# Summary
Kindly advise how do i tackle this question on streams, tried but couldn't figure it out.

## Description 
Shoutout to my githubber OuaiIsBien

## Suggested Answer (if any):
I tried the following `return IntStream.rangeClosed(1, n).map(x -> new Circle(new Point(x, n - x)).collect(Collectors.toList());`

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/82226334/115585751-78fa6200-a2fe-11eb-9b2f-aea2ae871f34.png)

**Comment by ShyamalSankar** [comment]
Heres something you may want to start with.
getCircles(int num)
Stream.iterate(1.0, x -> x <= num, x -> x + 1).map(x -> new Point(x, num - x + 1))....

**Comment by chamath2030** [comment]
> Heres something you may want to start with.
> getCircles(int num)
> Stream.iterate(1.0, x -> x <= num, x -> x + 1).map(x -> new Point(x, num - x + 1))....

thx i got it > return Stream.iterate(1, x -> x <= n, x -> x + 1).map(x -> new Point(x, n - x)).map(y -> new Circle(y)).collect(Collectors.toList());
