### ISSUE TITLE
Level 5 Test Case 5_11

### ISSUE THREAD

**Issue by jiahuitan36** [nus-cs2030/2021-s2#297]
Facing the following issue for test case 5_11 but I'm not sure how I can fix it. Did anyone face the same issue?

<img width="516" alt="Capture" src="https://user-images.githubusercontent.com/60168038/115652248-77ad5180-a35f-11eb-81eb-472c4d1a1a39.PNG">

**Comment by yx0555** [comment]
Not sure if you have solved this issue, but I suggest checking your done events to see if the server is free after serving. If not there may be a problem with your implementation of greedy customers such that they are not joining the correct server queue. Try to check using your own test case with all greedy customers!

**Comment by ShyamalSankar** [comment]
Looks like the queue of Server 1 is not full when it is supposed to be full. You may want to check if your server prematurely takes in the next Customer before finishing resting.

**Comment by random689** [comment]
If its not any of the above, it might be how your greedy customer is choosing the queue as well if you still have not solve it!
