### ISSUE TITLE
Accessing test caseslocally

### ISSUE THREAD

**Issue by yan-yushan** [nus-cs2030/2021-s2#30]
Any idea how to download the jshell test case files for lab locally? I can't seem to be able to access it using jshell -q < test1.jsh outside of my lab session. When I try to access the PE node via Sunfire, it says that connection has been closed.

(sorry for the missing spacing in the title!)

**Comment by lee97matthew** [comment]
You can go to CodeCrunch and under "My Submissions" you can "View details" for lab 2 and download them individually from the "
"Submission Files" tab.
