### ISSUE TITLE
1920 Sem 2 PYP

### ISSUE THREAD

**Issue by chamath2030** [nus-cs2030/2021-s2#300]
# Summary
Hey guys, able to advise what you think is the output for the following question? from my understanding, an interface cannot be instantiated and thus `I i = b;` should be invalid.  Therefore, the method `foo(I i)`  should be invalid too? since there will never be an object I. 

## Suggested Answer (if any):
153?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/82226334/115664495-7c303500-a374-11eb-8aa3-9702a84ec721.png)

**Comment by e0564330** [comment]
Hello, even though you can't instantiate an interface, it is still "like a type", hence I i = b should be valid as B implements I. You can try it out in java if you want it should work!

**Comment by gracefour11** [comment]
When you define a new interface, you are defining a new reference data type. You can use interface names anywhere you can use any other data type name. If you define a reference variable whose type is an interface, any object you assign to it must be an instance of a class that implements the interface.

^Taken from [Java Documentation](https://docs.oracle.com/javase/tutorial/java/IandI/interfaceAsType.html#:~:text=You%20can%20use%20interface%20names,class%20that%20implements%20the%20interface.&text=By%20casting%20object1%20to%20a,can%20invoke%20the%20isLargerThan%20method.)
