### ISSUE TITLE
CS2030 AY19/20 Sem 2 Q5 Anonymous Class

### ISSUE THREAD

**Issue by jcng2308** [nus-cs2030/2021-s2#309]
# Summary
Hello! Can anybody share how they did this question?

## Description 
I have always known about the simplification from concrete -> anonymous -> lambda. But when prompted to reverse engineer it, I can't seem to think of a method

## Suggested Answer (if any):
using apply?

## Screenshots (if any): 
Insert Images here if necessary
![2021-04-23 (2)](https://user-images.githubusercontent.com/64765004/115860512-305cb900-a464-11eb-933e-9474e19985c9.png)
![2021-04-23 (3)](https://user-images.githubusercontent.com/64765004/115860517-318de600-a464-11eb-9742-169ab5b10c4b.png)

**Comment by gracefour11** [comment]
i think for the first one, it's this.

`BiFunction<Character, String, Integer> s = new BiFunction<Character, String, Integer>() {
     @Override
     public Integer apply(Character i, String j) {
          return (i + j).length();
     }
}
`

**Comment by ruthkangyr** [comment]
As for the second one, I think its 
```
BiFunction<Double, Float, Long> r = new BiFunction<Double, Float, Long>() {
@Override
public Long apply(Double a, Float b) {
return Math.round(a + b);
}
}
```

**Comment by ivankqw** [comment]
Hi, you can refer to lecture 8 slides for more examples on how to create anonymous classes.
