### ISSUE TITLE
Level 5 NullPointerException

### ISSUE THREAD

**Issue by Roystal** [nus-cs2030/2021-s2#312]
Hey guys im facing an issue with the implementation of my level 5, getting a NullPointerException whenever I run the genRandomRest() or the genServiceTime() methods through this intermediate class that's supposed to pass the rest times and service times into my Main method. 

I could only pinpoint that the error occurs when I do rg.genRandomRest(), but I have no idea why this happens. Thanks for the help in advance!

<img width="417" alt="Screenshot 2021-04-24 at 4 04 47 AM" src="https://user-images.githubusercontent.com/62516317/115924459-514bfb00-a4b2-11eb-81fd-4556bd511055.png">

rg is the random generator that I instantiated through this intermediate class

<img width="603" alt="Screenshot 2021-04-24 at 4 04 59 AM" src="https://user-images.githubusercontent.com/62516317/115924450-4e510a80-a4b2-11eb-9bf8-9831cdbcf851.png">

**Comment by somenobody98** [comment]
Hi, chances are you did not initiate ur RandomGenerator _rg_ or _probRest_ correctly at the front, leading to a _NullPointerException_ when you try to use it to either _genRandomRest_ or _probRest_. The error shows that the null object is at line 26 in _restFor_, so you can use that to find out where the null is, or possibly at line 41 in your Main5.
