### ISSUE TITLE
Hidden Test Case 4_3

### ISSUE THREAD

**Issue by rljw** [nus-cs2030/2021-s2#314]
I am facing an error for test case 4_3, but I'm not too sure what's wrong, or how I can debug this given that my value is only off by a little. Anyone faced a similar issue and knows what to do?

![image](https://user-images.githubusercontent.com/79345598/115945286-a22d1500-a4ed-11eb-806d-a9369a84dcc1.png)

**Comment by eugenechua94** [comment]
Potentially might be one, or a combination of the 2 following issues: 

1. The way/order you generate the done and serve event (your line 58 and 59 - how can server 2 serve 17 first before done 15?);
2. The order rest time was taken in after the done event, which affects the serve time.

You can try printing out your array of customers / servers with the required info after printing every event to troubleshoot which part went wrong, might not be the best way, but works for me.

**Comment by jesslynlee** [comment]
hello, you might want to refer to #238 for the test case to help you debug

**Comment by brennanleez-coder** [comment]
Hi, can i clarify how you made your server's pickup the rest times

**Comment by rljw** [comment]
I've managed to solve it, thanks for the help!
