### ISSUE TITLE
Hidden Test Case 5_4 Issue

### ISSUE THREAD

**Issue by Roystal** [nus-cs2030/2021-s2#322]
Hey Guys, I am having a problem with my code for one of the hidden test cases, and I can't seem to figure out why:

<img width="687" alt="Screenshot 2021-04-24 at 8 53 19 PM" src="https://user-images.githubusercontent.com/62516317/115959523-383d5b80-a53f-11eb-9d4d-21b7f2358020.png">

Currently, my code has been pre-determining the done events during the serve event, and I overcome the issue of rest times and also the inability to draw the service time for the random generator until the done event, by peeking at the next event and subsequently removing and replacing it if the server NextAvailableTime < peeked event time.

This has worked well for all the given test cases, but it fails at the hidden test case 5_4.

I think the issue lies because I'm always referencing the state of the previous event, which may be outdated, and I think in this case it referenced the Serve Event for Customer 10's old state, so, therefore, resulting in the wrong next available timing for the server. But I have no idea how to circumvent this issue if this is the case...

**Comment by random689** [comment]
I also call the done event after the serve event as well but it works so its probably how you implemented it. From your output it seems that your code is causing the server to serve both 8 and 11 in his queue at the same time once the previous one is done instead of just moving up the queue.

**Comment by Roystal** [comment]
> I also call the done event after the serve event as well but it works so its probably how you implemented it. From your output it seems that your code is causing the server to serve both 8 and 11 in his queue at the same time once the previous one is done instead of just moving up the queue, and even skipped 10 so its probably how you "moved" up the queue that is causing the problem

Can I ask how do you go about removing and replacing the event? Do you peek at the prev event and then subsequently use its state to draw out the next available timing?

**Comment by random689** [comment]
My server each has a "queue" which i use to handle the customers and will only call the next serve event once the done event is called, but it seems that your code calls the serve event before the done event is even completed.

**Comment by lokehsienjie** [comment]
Perhaps look into your implementation of how u enqueue the next Serve event for each customer. The logic there probably enqueued customer 11's serve event prematurely/at the wrong time(depending on ur implementation). If its scheduled at the wrong time, consider how you catered for the server serving everyone in queue before customer 11, and whether you factored that into the calculation of the time. Lastly, try using print statements in your debugging and test with your own custom test cases to see if the logic is always right! Hope this helps

**Comment by Roystal** [comment]
@random689 @lokehsienjie Thanks! Managed to pass through the test cases!
