### ISSUE TITLE
17/18 Sem 1 Q6

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2030/2021-s2#324]
<img width="727" alt="q6" src="https://user-images.githubusercontent.com/67496158/115960710-8ead9880-a545-11eb-8fdd-7c684966a961.png">

## Description 
Both options D and E seem to work in Jshell. Which one is correct and why? Thanks!

**Comment by Xeph-o** [comment]
Both are accepted actually :) See - https://nus-cs2030.github.io/1718-s2/final/index.html

**Comment by zihaowrez** [comment]
Thank you!
