### ISSUE TITLE
Issue with test case 5_4

### ISSUE THREAD

**Issue by ilrbats** [nus-cs2030/2021-s2#325]
Hi, I am currently facing this error and I cannot figure out why this is happening.
![image](https://user-images.githubusercontent.com/13448644/115961006-11832300-a547-11eb-852f-8daac09003d0.png)

My suspicion is that I may be using a wrong comparator formula, however, when I tested out the comparator alone, the event "109.730 694(greedy) done serving by server 5" comes before the event "109.730 742 arrives". Moreover, I am quite certain the comparator formula I used is accurate as it would have failed before around the previous levels. 

Also for some context for my code, my code reads the Priority Queue by:
1.  assigning an event thisEvent = pq.remove()
2.  inserting the next event in the pq, or pq.add( thisEvent.next() )
3.  printing out the event
so I don't think it would be the case of adding the done event too late.

Also, my events flow in this manner:
1. Add all arrive events in the queue first
2. If no space, 
  Arrive -> Leave
3. If no free server,
  Arrive -> Wait (record which server queue the customer is in)
4. If there's a free server,
  Arrive -> Serve -> Done -> Serve (next customer in server queue) -> Done ... until server queue is empty

**Comment by clementyee303** [comment]
This is just a guess, but you should do a `less than` check and return `-1` for your comparator instead of just subtracting. Perhaps the subtraction is being rounded down?

**Comment by zhuoyunhui** [comment]
You could have rounded off the timings for each event somewhere in your code. If I'm not wrong the timings should only be rounded to 3dp when printing the event, and should be kept in the original form when comparing

**Comment by somenobody98** [comment]
If you are comparing the time, you could try using Double.compare(time1, time2) which should more accurate than using the standard operators, because I faced a similar issue that only surfaced in higher levels (when there was larger timings involved). Subtraction between two large double that are very close to each other is very inaccurate, so I believe that the Double.compare method is more accurate?

**Comment by raihanyusri** [comment]
Not sure if you already have this in your comparator, but for mine I had an additional check to see if the timings of event1 and event2 are equal. If they are equal, the event with smaller customer id should be printed first

**Comment by ilrbats** [comment]
Ok, I followed your advices, and it works now. Thanks for your help!
