### ISSUE TITLE
Level 5 "Extra bytes at the end of class file" error during runtime

### ISSUE THREAD

**Issue by Martini-Chwang** [nus-cs2030/2021-s2#343]
Hello! I'm currently doing Project level5 and am unable to run when my Main method tries to create a new MyRandomGenerator. 

javac works fine, the error only appears when I tried to run Main5 with the test case inputs.

![help1](https://user-images.githubusercontent.com/76718059/115990287-f2db6580-a5f4-11eb-956a-8565b6bcdb93.PNG)

**Comment by ryantjx** [comment]
Hi, could you take a screen shot of how you generated your RandomGenerator in Main?

It is also good to note that you will not be able to create a RandomGenerator object in Main as the method/constructors are not public. What I did was create a container class for RandomGenerator and declare my method/constructors public in that class.

**Comment by lyntanrambutan** [comment]
Hi, seems like your container class for RandomGenerator is MyRandomGenerator, maybe you want to check if all the methods/constructors are public in that class? Another reason could be there's an incompatibility in Java compiler and Java runtime used. Check the versions using java -version and javac -version.

**Comment by Martini-Chwang** [comment]
> Hi, seems like your container class for RandomGenerator is MyRandomGenerator, maybe you want to check if all the methods/constructors are public in that class? Another reason could be there's an incompatibility in Java compiler and Java runtime used. Check the versions using java -version and javac -version.

Hello! So my methods are all public and my java -verseion == javac -version. (11.0.9.1). Now am rly losted why it ain't working @.@

**Comment by Martini-Chwang** [comment]
> Hi, could you take a screen shot of how you generated your RandomGenerator in Main?
> 
> It is also good to note that you will not be able to create a RandomGenerator object in Main as the method/constructors are not public. What I did was create a container class for RandomGenerator and declare my method/constructors public in that class.

Yepp I have a container class MyRandomGenerator, eg method.
public double genInterArrivalTime() {
    return new RandomGenerator(this.seed, this.lambda, this.mu, this.rho).getInterArrivalTime();
}

**Comment by Martini-Chwang** [comment]
Okay probelm solved? I re-downloaded the RandomGenerator.class and it works now. Prolly corrupted my prev file by accident or sth ooops
