### ISSUE TITLE
PYP Solutions

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2021-s2#346]
Not sure if it was asked previously, but are there any solutions provided for the 2030 PYPs?

**Comment by clementyee303** [comment]
https://nus-cs2030.github.io/1718-s2/final/index.html

**Comment by zhiqixn** [comment]
Are there only solutions provided for 17/18? Based on the link, I seem to only be able to find that year's solutions

**Comment by clementyee303** [comment]
> Are there only solutions provided for 17/18? Based on the link, I seem to only be able to find that year's solutions

To my knowledge, I think that's the only available one. I just found out about it today too

**Comment by yueyin22** [comment]
Thanks guys!
