### ISSUE TITLE
Level 4 Hidden level

### ISSUE THREAD

**Issue by lohdaijiu** [nus-cs2030/2021-s2#354]
# Summary
Put a summary of the question
Wondering why does my next available time decrease after an arrival event. I tried lots of methods and checked my code but I don't know why it happens. Any idea?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/77648872/116002839-18389580-a62e-11eb-8341-32b1ba06bf87.png)
x, y
x indicates the server number and y indicates the nextAvailTime.

**Comment by High325** [comment]
It seems that when the doneServing event is triggered and the Server goes on rest it doesn't update the Server properly in your List/Array of Servers, but it's difficult to tell what the exact problem is from just the results of the test case. Either that or you are resetting your server nextAvailTime somehow in your arrival event

**Comment by yx0555** [comment]
Have you taken into consideration the rest-times and service times of previous customer when outputting nextavailtime? Make sure the server array is updated when you call Done event too.

**Comment by ck-109** [comment]
Based on your test case when id 13 arrives, your server next arrival time probably the result of (customer arrival time + ...) OR (event time + ...). You can try update the server's next available time after done event then call this instead (next available time + ... )

**Comment by lohdaijiu** [comment]
Hi all, thanks for replying

When my arrive event triggers the Wait Event, there is no change in my nextAvailTime for my server. As a result, I would assume it to have the same nextAvailTime.
![image](https://user-images.githubusercontent.com/77648872/116005672-9864f800-a63a-11eb-8d99-adacb9ad95b7.png)

**Comment by lohdaijiu** [comment]
My Rest event correctly update the Server nextAvailTime as shown by the 14.64.
This will create a RestDone event in the PQ to be executed later. The arrive event is the only one that might change the nextAvailTime of my server. But after multiple checks, I do not think that Arrive event is the cause of the change in nextAvailTime. So I am kind of stucked.
