### ISSUE TITLE
Anonymous Class

### ISSUE THREAD

**Issue by joleneleee** [nus-cs2030/2021-s2#359]
I am not too sure how to create anonymous classes. Can someone kindly share?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/77771857/116027915-a04b8900-a688-11eb-965c-ed3bfd97a4a1.png)

**Comment by gracefour11** [comment]
Hi, u can refer to [#309 ](https://github.com/nus-cs2030/2021-s2/issues/309#issue-865997466)

**Comment by eltonngkk** [comment]
It would be 
```BiFunction<String, Integer, String> c = new BiFunction<String, Integer, String>() {```
```@Override```
```public String apply(String x, Integer y) {```
```return String.format("%s:%d", x, y);```
```}```
```}```
