### ISSUE TITLE
1819 Sem2 Q.17 (IntStream)

### ISSUE THREAD

**Issue by salteefish** [nus-cs2030/2021-s2#363]
# Summary
Put a summary of the question here

## Description 
Does anyone know how to answer this question?

## Suggested Answer (if any):
Post your answer or the suggested answer, if any. 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/77676099/116048888-4064da80-a6a8-11eb-827e-f69c467c0d66.png)

**Comment by jesslynlee** [comment]
hello, you might want to refer to #315

**Comment by salteefish** [comment]
Thanks for the help!
