### ISSUE TITLE
1819 Sem1 Paper Q.3

### ISSUE THREAD

**Issue by salteefish** [nus-cs2030/2021-s2#364]
# Summary
Put a summary of the question here

## Description 
Anyone knows how to do this question? Taken from 1819Sem1 Paper. 

## Suggested Answer (if any):
Post your answer or the suggested answer, if any. 

## Screenshots (if any): 
![Screenshot 2021-04-26 175235](https://user-images.githubusercontent.com/77676099/116064179-58dcf100-a6b8-11eb-896a-b0a5da750d4c.png)
![Screenshot 2021-04-26 175301](https://user-images.githubusercontent.com/77676099/116064192-5a0e1e00-a6b8-11eb-8947-4aa1feb89b30.png)

**Comment by brendancjz** [comment]
static Optional<MinMax> findMinMax(Stream<Integer> intstream) {
return intstream.map(x -> new MinMax(x, x)).reduce((x,y) -> new MinMax(Math.min(x.min, y.min),Math.max(x.max,y.max)));
}

Intuition is to map the Integer into MinMax objects and then reduce them using the one-argument reduce method to return an Optional. Hope this helps.

**Comment by OuaisBien** [comment]
```
static Optional<MinMax> findMinMax(Stream<Integer> instream) {
        return Optional.ofNullable(instream.reduce(new MinMax(Integer.MAX_VALUE, Integer.MIN_VALUE),
            (minmax, i) -> new MinMax(Math.min(minmax.min, i), Math.max(minmax.max, i)), (minmax, i) -> minmax))
            .map(x -> {
                if (x.min == Integer.MAX_VALUE && x.max == Integer.MIN_VALUE) {
                    return null;
                } else {
                    return x;}});
}
```
My approach was similar to the way i solved normalized mean in the lab. If the seed MinMax(Integer.MAX_VALUE, Integer.MIN_VALUE) is not modified at all, an Optional.empty will be returned.

**Comment by salteefish** [comment]
Thanks guys for the help, much appreciated!
