### ISSUE TITLE
AY1819 Sem 1 Q3: findMinMax

### ISSUE THREAD

**Issue by somenobody98** [nus-cs2030/2021-s2#374]
# Summary
Other possible solutions?

## Description 
Does anyone have any other alternative solutions to mine? Mine works and seems logically true too. However, I feel that it is too lengthy and sort of hardcoding. However, the question did mention that we are not allowed to use any Java collections so that made it harder, and the fields in MinMax are final. It also seems like we cannot add methods into MinMax. 

## My Answer:
![image](https://user-images.githubusercontent.com/77392099/116115180-b55a0380-a6ec-11eb-8edb-49ed3c12c37e.png)

## Question: 
![image](https://user-images.githubusercontent.com/77392099/116114943-7035d180-a6ec-11eb-855c-2eb5fccb6730.png)

**Comment by clementyee303** [comment]
#363 Check out this thread

**Comment by somenobody98** [comment]
> #364 Check out this thread

Hi, ps missed that out, thanks for the link!
