### ISSUE TITLE
AY2021 Sem 1: Q2 Generics

### ISSUE THREAD

**Issue by somenobody98** [nus-cs2030/2021-s2#377]
# Summary
Jshell can't find my method?

## Description 
Does anyone know why jshell cannot find the method `replace`? I do not think my solution has any issues? Also imported everything  Or is it my test case producing the problem? Thank you!

## My Answer:
![image](https://user-images.githubusercontent.com/77392099/116131189-a8461000-a6fe-11eb-988d-95fbbc0b9a8a.png)

## Question: 
![image](https://user-images.githubusercontent.com/77392099/116131241-b72cc280-a6fe-11eb-9758-6546bd21745e.png)

**Comment by lyntanrambutan** [comment]
When you wrote the function replace in jshell, did it give something like

created method replace(List<? extends T>,List<? super T>,BiPredicate<? extends T,? super T>), however, it cannot be referenced until class T is declared

**Comment by somenobody98** [comment]
Ya, I just tried it and it did. I understand why jshell would do that, but how do I go about this? 
And what do you mean by "adding a at the start of the method signature"?

**Comment by JYLim99** [comment]
I believe lyntanrambutan suggest declaring `<T>` at the start of the method. 
So it should be something like `<T>` void replace(List<? extends T> ...) since currently the variable T is not being declared within the method/class

**Comment by chence08** [comment]
Both your `src` and `dst` should be of type `List<T>`.

Then you can try:

`<T> void replace(List<T> src, List<T> dst, BiPredicate<T, T> pred)`

**Comment by somenobody98** [comment]
> I believe lyntanrambutan suggest declaring `<T>` at the start of the method.
> So it should be something like `<T>` void replace(List<? extends T> ...) since currently the variable T is not being declared within the method/class

Ahh I see, I just tried it but now I am getting this which seems weird? 
![image](https://user-images.githubusercontent.com/77392099/116179953-b91c7300-a74a-11eb-910f-09ceee755d08.png)

**Comment by eugenechua94** [comment]
Hi, the complication seem arise from the technicalities behind the design of jshell for testing.  

To overcome this you can try creating a class consisting of the replace method to test if your method works.

In addition you might need to define your src list type to only extend dst type <? extends T>, and keep dst list type to be fixed <T>, as the qn is asking for values in dst to be replaced by src list based on the criteria, and no need for the other way round. In this case a bipredicate might also not be necessary and a predicate or comparator will suffice. 

My 2 cents, hope it helps somewhat :)

**Comment by elitanzc** [comment]
Hello! I met this problem too when trying this question. I think it might got to do with the pecs principle coz the solution worked when I tried `<T> void replace(List<? extends T> src, List<T> dst, BiPredicate<? super T, ? super T> pred)` instead.
The `pred` is a consumer, so both arguments must be `? super T`, and for `src` it only produces so it must be `? extends T`. For `dst` it is both a producer (for the pred function) and a consumer (of src) so using `<T>` will do.

**Comment by ruthkangyr** [comment]
> Hello! I met this problem too when trying this question. I think it might got to do with the pecs principle coz the solution worked when I tried `<T> void replace(List<? extends T> src, List<T> dst, BiPredicate<? super T, ? super T> pred)` instead.
> The `pred` is a consumer, so both arguments must be `? super T`, and for `src` it only produces so it must be `? extends T`. For `dst` it is both a producer (for the pred function) and a consumer (of src) so using `<T>` will do.

can I ask how did your test case look like in this case?

**Comment by xnajasho** [comment]
Not sure if this is correct but heres how I did it
[](url)

**Comment by xnajasho** [comment]
Not sure if this is correct but heres how I did it
```
static <T> void replace(List<? extends T> src, List<T> dst, BiPredicate<? super T, ? super T> pred) {
    if (src.size() == dst.size()) {
        for (int i = 0; i < src.size(); i++) {
            if (pred.test(src.get(i), dst.get(i))) {
                dst.set(i, src.get(i));
            }
        }
    }
}
```
As for the test cases

```
List<Number> destination = new ArrayList<>(List.of(1, 2, 3));
List<Integer> source = new ArrayList<>(List.of(4, 5, 6));

System.out.println(destination);
replace(source, destination, (src, dst) -> true);
System.out.println(destination);
```

I believe using `Double/Integer` as the different `T` types are not compatible as if you look as the class hierarchy, both `Double/Integer` are subclasses of `Number`. So it will actually throw an error when you try to insert a type `Integer` into the `List<Double> destination`

**Comment by somenobody98** [comment]
> Hello! I met this problem too when trying this question. I think it might got to do with the pecs principle coz the solution worked when I tried `<T> void replace(List<? extends T> src, List<T> dst, BiPredicate<? super T, ? super T> pred)` instead.
> The `pred` is a consumer, so both arguments must be `? super T`, and for `src` it only produces so it must be `? extends T`. For `dst` it is both a producer (for the pred function) and a consumer (of src) so using `<T>` will do.

Hi, thanks for the explanation!! I get it!
