### ISSUE TITLE
AY2021 Sem1 PYP

### ISSUE THREAD

**Issue by xnajasho** [nus-cs2030/2021-s2#384]
Any kind soul willing to share a link/pdf version for the AY2021 Sem 1 PYP? Couldn't find it anywhere on nus-lib :/

**Comment by jordanwwb** [comment]
[questions.pdf](https://github.com/nus-cs2030/2021-s2/files/6381731/questions.pdf)

**Comment by emfancypants** [comment]
thank you!

**Comment by xnajasho** [comment]
> [questions.pdf](https://github.com/nus-cs2030/2021-s2/files/6381731/questions.pdf)

Thanks!
