### ISSUE TITLE
thenApplyAsync vs thenApply

### ISSUE THREAD

**Issue by lokehsienjie** [nus-cs2030/2021-s2#388]
Hi! Would just like to see if anyone can shed some light on when we use thenApplyAsync versus thenApply? Understand from the API that thenApplyAsync (or any then____Async) will execute using this stage's default asynchronous execution facility, whereas thenApply just executes. My understanding of this is that thenApplyAsync simply branch out to more threads that runs asynchronously from this point of execution on. However, since the CompletableFuture object is already being executed on a asynchronous thread, when is it important for us to use thenApplyAsync, and when is it better to use thenApply? Thank you!
![image](https://user-images.githubusercontent.com/78008592/116216596-5ee7d600-a77b-11eb-9519-fcfff29c1197.png)

**Comment by Qingyi1115** [comment]
Hi Hsien Jie! 
thenApplyAsync allows multiple task to run at the same times, so let's say method 1 uses thenApply, and method 2 uses thenApplyAsync. We can call method 2 multiple times, and it will be executed in different threads.  I tink :P

**Comment by liongthryan** [comment]
I found a helpful post that explains this concept well! 

https://stackoverflow.com/questions/47489338/what-is-the-difference-between-thenapply-and-thenapplyasync-of-java-completablef#:~:text=thenApply(fn)%20%2D%20runs%20fn,defined%20executor%20regardless%20of%20circumstances.

The question asked there is similar to yours, and I think the answers are all useful and descriptive. Hope this helps!

**Comment by lokehsienjie** [comment]
@Qingyi1115 ohh i see, thanks for the perspective!!
@liongthryan ahh nice this was rly useful in understanding the concept of the context. Thank you!
