### ISSUE TITLE
How to set up the output from Random Generator.

### ISSUE THREAD

**Issue by TMTM98** [nus-cs2030/2021-s2#392]
# Summary
Put a summary of the question
This is how I am extracting the output of RandomGenerator right now, but it only works on my PC and not in CodeCrunch.

Can someone tell me how it should be extracted into the arrays for the program to use?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/77833847/116238702-4b953480-a794-11eb-8f72-b307a7a90ac6.png)

**Comment by TMTM98** [comment]
There is not any issue in it running, but the output from Test5_1 but I can get the correct output from the first 2 test cases on the question page so I am guessing the **probability of resting, Pr** and  **probability of a greedy customer occurring, Pg** has something to do with it, how do I use those 2 variables since they are not taken in by the RandomGenerator?

![image](https://user-images.githubusercontent.com/77833847/116243816-ec3a2300-a799-11eb-82af-56df3ffea167.png)

**Comment by ryantjx** [comment]
There are some issues that I think will cause incorrect outputs,

Your service time is generated upon creation of a new Customer. Rightfully, the service time should be a Supplier<Double>, so it will only be called during the service of the customer.

To answer your qn on Pr and Pg,

.genCustomerType() will return a double. Then you use that to compare with Pg. If gen.genCustomerType() < Pg, then your customer will be a greedy customer.

You have to use .genRandomRest() before calling the genRestPeriod() to determine whether the server will rest.
If .genRandomRest() < Pr then your server will rest. Take note that .genRandomRest() will only be generated after a DONE event.

**Comment by yeetongg** [comment]
Hi, I think when you first create the new customer you cannot generate the service time because it's only supposed to be generated when the customer is served. I did the generation of the service time within the ServeEvent and not in the Manager class.

**Comment by TMTM98** [comment]
Would the time when it is generated actually affect the output? I have no issues with output if **probability of resting, Pr and probability of a greedy customer occurring, Pg** are 0, so I am suspecting it actually has something to do with that.

Here is the updated code:
![image](https://user-images.githubusercontent.com/77833847/116337240-65725e00-a80c-11eb-956f-d92dd8faff89.png)

**Comment by yeetongg** [comment]
> Would the time when it is generated actually affect the output? I have no issues with output if **probability of resting, Pr and probability of a greedy customer occurring, Pg** are 0, so I am suspecting it actually has something to do with that.
> 
> Here is the updated code:
> ![image](https://user-images.githubusercontent.com/77833847/116337240-65725e00-a80c-11eb-956f-d92dd8faff89.png)

Hi, yeah I think the time generated will affect the output because now you are generating the service times according to the customer id. So you are generating in the order of customer 1, customer 2 , customer 3. However if customer 1 is served after customer 3, then your service time would be wrong bc the service time should only be generated when it is being served, which is after customer 3, not pre-assigned which I think you did in your code.

**Comment by TMTM98** [comment]
I have modified the program to generate rest times only when there is a done event and an array of service times is generated in the constructor since even those customers who leave should have a service time and the program moves the count in the array by one each time there is a arrival event but I am still stuck at Test case 5_3. Any idea why?
![image](https://user-images.githubusercontent.com/77833847/116344681-40d0b300-a819-11eb-8b66-ef169386d752.png)

![image](https://user-images.githubusercontent.com/77833847/116344714-53e38300-a819-11eb-8d40-2b56a69f267c.png)

**Comment by TMTM98** [comment]
I think I have resolved this issue by doing the above @yeetongg , thank you very much.
