### ISSUE TITLE
1718S2 Extra Review Question (Stream of Functions)

### ISSUE THREAD

**Issue by davidwang98** [nus-cs2030/2021-s2#394]
# Summary
Does anybody know how to do this question?

## Suggested Answer (if any):
Does it have to do with iterating or generating a stream? My code is incomplete

```
Stream<Function<T,T> method(Function<T,T> f) {	
	return Stream.iterate(f, ???
}
```

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/71161461/116244131-34f1dc00-a79a-11eb-87bf-3659cf2c80f4.png)

**Comment by rendao1010** [comment]
Not sure if this works (works with the example given in the question in jshell), but this is what I came out with:

```
<T> Stream<Function<T,T>> generateStream(Function<T,T> f) {
    return Steam.iterate(f, x -> h -> f.apply(x.apply(h)));
}

<T> Stream<T> generateValues(Stream<Function<T,T>> s, T, t) {
    return s.map(y -> y.apply(t));
}
```

**Comment by ARPspoofing** [comment]
> Not sure if this works (works with the example given in the question in jshell), but this is what I came out with:
> 
> ```
> <T> Stream<Function<T,T>> generateStream(Function<T,T> f) {
>     return Steam.iterate(f, x -> h -> f.apply(x.apply(h)));
> }
> 
> <T> Stream<T> generateValues(Stream<Function<T,T>> s, T t) {
>     return s.map(y -> y.apply(t));
> }
> ```

may I ask where did the h come from and how did you get it? Thanks!

**Comment by OuaisBien** [comment]
I think h is just the input of another lambda. Think of it as `x -> { return h -> f.apply(x.apply(h)); }`

**Comment by kaiwenyay** [comment]
what i did was

**Comment by kaiwenyay** [comment]
there's actually a compose method defined in the function interface, which is what i used. so the function you pass into Stream.iterate() just becomes x -> x.compose(seed).
