### ISSUE TITLE
RandomGenerator is not public 

### ISSUE THREAD

**Issue by e0564085** [nus-cs2030/2021-s2#398]
# Summary
My compiler can find where RandomGenerator is, but when I initialize and use its methods, it returns an error saying that genServiceTime() is not public and cannot be used outside the package.  How can I solve this problem
I am pretty lost now. Please help me.
Thank you
![image](https://user-images.githubusercontent.com/80497923/116276195-dedf6180-a7b6-11eb-8355-317a8273a012.png)

**Comment by YuanZhengyz** [comment]
What I did was make a public Generator class that has a RandomGenerator, then construct a Generator instead of a RandomGenerator. Generator will have the methods genServiceTime() etc, which will just return the value generated from RandomGenerator inside it.

**Comment by chehoelau** [comment]
Hello, please refer to issue #362 on the placement of your source files. Essentially, your Main cannot be in the same directory as cs2030/simulation.

**Comment by chamath2030** [comment]
gdluck buddy less than 24 hrs left

**Comment by yeetongg** [comment]
Hi, I faced the same issue as you, but when I added the word "public" in front of the RandomGenerator constructor the error disappeared.

**Comment by chence08** [comment]
```java
public class RandomGeneratorImpl extends RandomGenerator {
    public RandomGeneratorImpl(...) {
        super(...);
    }
    
    public methodX() {
        super.genInterArrivalTime();
    }
}
```

```
your folder
├── Main1.class
├── Main1.java
├── Main2.class
├── Main2.java
├── Main3.class
├── Main3.java
├── Main4.class
├── Main4.java
├── Main5.class
├── Main5.java
├── Project.iml
└── cs2030
    └── simulator
        ├── ... all your .class and .java files
        ├── RandomGenerator.class
        ├── RandomGeneratorImpl.class
        ├── RandomGeneratorImpl.java
```

Hope this helps! All the best!

**Comment by andreathr** [comment]
https://github.com/nus-cs2030/2021-s2/wiki/Extending-Project-to-Level-5
u can try referring to this if it helps!

**Comment by linminsaw** [comment]
you can make a wrapper class of RandomGenerator and make everything public there. You can check this out #211

**Comment by e0564085** [comment]
@chehoelau @chence08 @linminsaw @YuanZhengyz @andreathr thanks guys!
