### ISSUE TITLE
Is working required for "expected output" type of questions?

### ISSUE THREAD

**Issue by SW-bza** [nus-cs2030/2021-s2#401]
# Summary
I realised some of PYPs have "expected output" type questions similar to CS1010. Will marks awarded for workings of this kind of questions or do we just need to write output only?

**Comment by yowyuxuan** [comment]
I believe we would only need to state the output.

**Comment by Buwoo** [comment]
I think best to follow instructions for the question itself if really come out in exam. Tentatively, from the pyps, it seems that they only mark the final ans with a bot

**Comment by chamath2030** [comment]
just read the paper carefully tmr, might be diff from prev sems

**Comment by audrey-eng** [comment]
Nope, just stating the output is fine based on some of the pyps

**Comment by e0543492** [comment]
Just read the instructions carefully during the exam.

**Comment by brendanlyc** [comment]
Best to read instructions, but i think only output needs to be stated.
