### ISSUE TITLE
1819sem1 qn5

### ISSUE THREAD

**Issue by eseutella** [nus-cs2030/2021-s2#402]
# Summary
Can anyone help me with this question? I tried to follow the format given in the RecursiveAction API but I am still quite lost on how to do :')

## Description 
Post the question that you would like your peers or seniors to answer. 

## Suggested Answer (if any):
Post your answer or the suggested answer, if any. 

## Screenshots (if any): 
Insert Images here if necessary
<img width="344" alt="Screenshot 2021-04-28 002738" src="https://user-images.githubusercontent.com/77688520/116278095-bbb5b180-a7b8-11eb-97c7-3f995eef3472.png">
<img width="275" alt="Screenshot 2021-04-28 002709" src="https://user-images.githubusercontent.com/77688520/116278098-bce6de80-a7b8-11eb-88fe-f407327fa3d0.png">

**Comment by gracefour11** [comment]
actually, i think this is out of scope for our finals

**Comment by chamath2030** [comment]
not tested, but good effort

**Comment by Jjjetplane** [comment]
I dont think this part is examinable!
