### ISSUE TITLE
AY20/21 PYP 

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2021-s2#403]
Has anyone completed AY20/21 PYP? Mind sharing your answers?

**Comment by chamath2030** [comment]
have u completed?

**Comment by yueyin22** [comment]
@chamath2030 
I don't get q1 and 2 at all, am working on q3 for now.

**Comment by rljw** [comment]
Hey, you can check out #382 for q1 and #377 #353 for q2. The discussions there may give you some useful hints to work with

**Comment by yx0555** [comment]
just an fyi, qns 4 and 5 will not be tested as they are on functors and lazylist. You may want to refer to #386 and #395 for question 6 as the comments are pretty helpful in explaining the concepts covered.

**Comment by yueyin22** [comment]
@rljw @yx0555 Thank you!
