### ISSUE TITLE
Writing of codes during exam

### ISSUE THREAD

**Issue by xnajasho** [nus-cs2030/2021-s2#412]
https://www.comp.nus.edu.sg/~cs2030/exam/

Based the thread above, are we allowed to use IDEs like IntelliJ to write out our answers (since VScode is accepted)

**Comment by Martini-Chwang** [comment]
Yepp, 'use whatever means to write your answer'

**Comment by deniselam10** [comment]
yes u can !

**Comment by xnajasho** [comment]
Alright thanks ! :)
