### ISSUE TITLE
Reference to (pre-downloaded) External Webpages/Notes during Final?

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2021-s2#413]
Besides our own course materials, can we refer to external (pre-downloaded) notes during the final? E.g. from www.geeksforgeeks.org

**Comment by isaactyj** [comment]
Nope we cant. codecrunch,luminus and java api website only. I think unless you download the webpage as a HTML? Dont quote me on this

**Comment by yueyin22** [comment]
@isaactyj PDF?

**Comment by Cassianky** [comment]
_The exam is open book.  You can refer to hardcopy notes (or softcopy, provided these are viewable on the same machine that you use to take the exam, i.e. they have to be captured by the screen recording)._  I think a downloaded file is okay, no access to websites other than those stated above

**Comment by W-ShiHan** [comment]
PDF should be fine if you save them as "softcopy notes"

**Comment by yueyin22** [comment]
@isaactyj @Cassianky @W-ShiHan
Okay! Thanks!

**Comment by isaactyj** [comment]
Might want to ask on the excel sheet for more clarity

**Comment by isaactyj** [comment]
My TA just replied that it is cheating if we do so
