### ISSUE TITLE
How to adapt to using main() for PE?

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2030/2021-s2#51]
I have been attempting CS2030 Mock Practical Assessment #1: Salary. I have written all classes I need. I have also copied and modified the `Main` class, but I have no idea how I can run the main() function. I have tried the following code to run in jshell.
```
javac *.java
jshell *.java < Main.java
```
However, jshell only creates the class Main (as shown in the figure).
<img width="488" alt="Screenshot 2021-02-25 145941" src="https://user-images.githubusercontent.com/67496158/109115517-29723c80-777a-11eb-9958-51251d967d92.png">
I don't think the main() function is executed because there are no expected outputs or errors.

I have also tried to submit all the .java files on CodeCrunch, but I get a compilation error 
```
gcc: error trying to exec 'ecj1': execvp: No such file or directory
```

I'm not sure what I'm supposed to do. Any helps? Should I run these code to create a jar archive?
```
$ jar cvf salary1.jar *.java
$ mkdir salary1
$ cp *.java salary1
$ cp salary1.jar salary1
```

**Comment by raymondtanujaya** [comment]
Use `java Main < test1.in` to see output of your main class given `test1.in`. You can compare it to the expected output in codecrunch.

 There is nothing much to do with jshell if you already have Main class. All output should be printed out when input is given to the Main.

**Comment by tlylt** [comment]
Hello, so if you want to test your code on your local machine:
- create `Main.java` file and copy the content of the `Main` class in from the codecrunch task description. (`Main` is a Java class)
- create `test1.in` by `vim test1.in` and copy in the underlined inputs
- create `test1.out` by `vim test1.out` and copy in the none underlined outputs (reference below)
![image](https://user-images.githubusercontent.com/41845017/109130791-174dc980-778d-11eb-8424-ea99e95d5cc7.png)
- then run `java Main < test1.in | diff - test1.out` in your command line

**Comment by jordanwwb** [comment]
hi, if im not wrong you do not need jshell to run Main.java. 
You can try `java Main` followed by typing out the input given by the question.
OR
You can copy the underlined content and make a new file test1.in, followed by the output content in a new file test1.out.
Doing so you will be able to execute `java Main < test2.in | diff - test2.out`

**Comment by dumbasssoul** [comment]
hello i tried `java Main < test1.in | diff - test1.out` and my output was:
`Error: Could not find or load main class Main
Caused by: java.lang.ClassNotFoundException: Main
0a1,7
> Mohammad Ali: salary is 24K, annual raise is 11%
> Steve Gates: salary is 36K, annual raise is 5%
> Michael Jordan: salary is 71K, annual raise is 7%
> Lora Star: salary is 104K, annual raise is 2%
> Donald Kim: salary is 44K, annual raise is 1%
> Bill Jobs: salary is 54K, annual raise is -2%
`
why is there the error though the output is correct?

**Comment by tlylt** [comment]
> hello i tried `java Main < test1.in | diff - test1.out` and my output was:
> 
> `Error: Could not find or load main class Main Caused by: java.lang.ClassNotFoundException: Main 0a1,7 Mohammad Ali: salary is 24K, annual raise is 11% Steve Gates: salary is 36K, annual raise is 5% Michael Jordan: salary is 71K, annual raise is 7% Lora Star: salary is 104K, annual raise is 2% Donald Kim: salary is 44K, annual raise is 1% Bill Jobs: salary is 54K, annual raise is -2%`
> why is there the error though the output is correct?

Can you verify that you have created the class `Main` in `main.java` file, together with your other files?

**Comment by nicolaineo** [comment]
Does anyone know if this means we have to use Main classes in the upcoming PE? Considering that we have not used it at all thus far in our Labs or Recitations

**Comment by dumbasssoul** [comment]
> > hello i tried `java Main < test1.in | diff - test1.out` and my output was:
> > `Error: Could not find or load main class Main Caused by: java.lang.ClassNotFoundException: Main 0a1,7 Mohammad Ali: salary is 24K, annual raise is 11% Steve Gates: salary is 36K, annual raise is 5% Michael Jordan: salary is 71K, annual raise is 7% Lora Star: salary is 104K, annual raise is 2% Donald Kim: salary is 44K, annual raise is 1% Bill Jobs: salary is 54K, annual raise is -2%`
> > why is there the error though the output is correct?
> 
> Can you verify that you have created the class `Main` in `main.java` file, together with your other files?

yep i copy pasted the code from codecrunch into Main.java and didnt make any changes to it

**Comment by raymondtanujaya** [comment]
comment out all your codes except given from codecrunch and see whether it works

**Comment by zihaowrez** [comment]
Thank you all for answering. I submitted my codes to the updated tasks on CodeCrunch and I didn't encountered any technical issues.

> Does anyone know if this means we have to use Main classes in the upcoming PE? Considering that we have not used it at all thus far in our Labs or Recitations

I think so, but I think a Main class will be given, and maybe you need to make some changes if necessary.

**Comment by gableejh** [comment]
> Does anyone know if this means we have to use Main classes in the upcoming PE? Considering that we have not used it at all thus far in our Labs or Recitations

I believe Prof Henry said no during the consultation session earlier! You can double check from the recording

**Comment by Keithlimhs** [comment]
> Does anyone know if this means we have to use Main classes in the upcoming PE? Considering that we have not used it at all thus far in our Labs or Recitations

Hi i think we do not have to use? The lab 3 that we did was a past year practical exam so i think it would follow the format we had been doing in lab

**Comment by yuyitan** [comment]
I got the same compilation error at first, but then I tried submitting my code level by level (there is a small hyperlink you can click under each level to submit your code) and it worked.

**Comment by Archduck4** [comment]
> > > hello i tried `java Main < test1.in | diff - test1.out` and my output was:
> > > `Error: Could not find or load main class Main Caused by: java.lang.ClassNotFoundException: Main 0a1,7 Mohammad Ali: salary is 24K, annual raise is 11% Steve Gates: salary is 36K, annual raise is 5% Michael Jordan: salary is 71K, annual raise is 7% Lora Star: salary is 104K, annual raise is 2% Donald Kim: salary is 44K, annual raise is 1% Bill Jobs: salary is 54K, annual raise is -2%`
> > > why is there the error though the output is correct?
> > 
> > 
> > Can you verify that you have created the class `Main` in `main.java` file, together with your other files?
> 
> yep i copy pasted the code from codecrunch into Main.java and didnt make any changes to it

Hi, I am in a similar position for this, anyone knows how to move forward from here?
