### ISSUE TITLE
Override tag on child methods causing errors

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#53]
While doing the Practice Chatbot Problem, I encountered several errors on Codecrunch because of Override tags on child methods. Once I removed them, everything works fine. However, I thought it is good practice to always put the Override tag on methods in the child class that has its own version of the same method as its parent class. 

Parent class:
```
class Command {
    String execute() {
        return "Hello";
    }
```

Child class with override tag on the same execute() method:
```
class SongCommand extends Command {
    @Override
    String execute() {
    	if (bot instanceof PoliceChatbot && hasBadInput()) {           
    		return "Angry " + bot.getName() + " sings: Like a Rolling Stone ...";  	   
        }
        return bot.getName() + " sings: Like a Rolling Stone ...";
    }
}
```
Codecrunch says 'method does not override or implement a method from a supertype' when the Override tag is there. I am not sure why that is the case.

Did anyone encounter the same issue? And can someone clarify on when should we put the Override tag on child methods (aside from toString())? Thank you!

**Comment by KingRyo13** [comment]
I ran your code and got no error with the overriding actually. Maybe check that you didn't accidentally put @Override in both your super and child class and that the child is extending the correct parent? 

We put @Override tags on child methods for situations where the child wants to call the same method as the parent but has a different implementation of the method. For example 2 classes, Circle and Rectangle that extends a parent class Shape, would have 2 different ways to compute area. Hence, the getArea() method in Shape will be overridden by both the Circle and Rectangle classes to suit to their own calculations.

**Comment by jordanwwb** [comment]
There might be some typo on the method you are trying to override. The methods on both the parent and child needs to be the same for the method to override. 

The compiler checking to make sure you actually are overriding a method when you think you are. This way, if you make a common mistake of misspelling a method name or not correctly matching the parameters, you will be warned that you method does not actually override as you think it does.

**Comment by markwty** [comment]
I think the problem here isn't about your syntax but how the checking is carried out in CodeCrunch. The backend may have substituted a new Command class to test for whether the Command class is abstract (which should be the case since Command does not exist on itself & so does its execute method) or for more targeted testing. When compiled against your Command subclasses, there is no "overridden" method & hence the error. And this also explains why it manages to pass when the @Overriden tag is removed.

**Comment by gableejh** [comment]
Your code looks fine to me, not sure what is causing the error. As for when to add an override tag, on child classes where you implement the same method in the parent class to let the compiler know (and help verify).

**Comment by etbf** [comment]
Your code seems fine. Just ensure your method signatures are the same.
