### ISSUE TITLE
How to check if a string contains only null values? (PA1)

### ISSUE THREAD

**Issue by Zifengzf** [nus-cs2030/2021-s2#58]
In my in lab attempt, I constructed the toString method of Token via:
 if (this.pings.length == 0) { 
     return String.format("Token #%d: none", this.identifier); 
}

Having changed the constructor of Token to create new int[20] to facilitate ordering of identifiers, I am wondering if there is simple way to check if an array contains only null values to make the minimal modifications to my code?

Thank you!

**Comment by gableejh** [comment]
If I'm not wrong, I believe that when an integer array is initialised, the default values are set to 0. So to check if it's null, it should be checking if it is equivalent to 0.

**Comment by Zifengzf** [comment]
I just realised the default values are zero! Thanks!
