### ISSUE TITLE
Dependency on java library detected.

### ISSUE THREAD

**Issue by marvinljw** [nus-cs2030/2021-s2#59]
Hi, I did not include any import statements into my code but when I submit it, it shows that I have dependency on java library.
Does anyone know how to resolve this issue? Much thanks :)

**Comment by miao-tianjia** [comment]
I remember that Java will import java.lang by default (even if you do not explicitly write "import java.lang.*" in your code). Just double-check that you did not use any method such as Math in your code. Hope this helps!

**Comment by gableejh** [comment]
Run through all of your code files again to ensure that there are no import statements and yes, java.lang is automatically imported

**Comment by Onelayer** [comment]
As others have mentioned above, java.lang is automatically imported so make sure that you did not use any System.out.println statements as its a final class defined in the java.lang.package. Hope this helps!

**Comment by kexinnnwang** [comment]
Hi I've faced a similar problem and seems to have resolved once I removed System.out.println statements

**Comment by Keithlimhs** [comment]
Check through your code to ensure that you did not use any methods from any package. Most likely it may be the use of System.out.println statement in your code

**Comment by bonsibyl** [comment]
yup removing System.out.println should fix that error. Try using your store method that you defined for your registry instead!

**Comment by marvinljw** [comment]
Yes, removing the System.out.println does fix the error. Thanks guys!
