### ISSUE TITLE
Error: Missing a Javadoc comment

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2030/2021-s2#62]
Hi, when I submit my codes including a Main class on CodeCrunch, I encounter this error:

<img width="437" alt="javadoc" src="https://user-images.githubusercontent.com/67496158/110945431-a4417700-8378-11eb-9ea7-e6272a9bb491.png">

What does this mean? What should I do? Thank you!

**Comment by vishandi** [comment]
Hi! What assignment are you working on? If it was the project, you should include a Javadoc comment for all public methods (The tutor mentioned it earlier in the lab).

**Comment by zihaowrez** [comment]
> Hi! What assignment are you working on? If it was the project, you should include a Javadoc comment for all public methods (The tutor mentioned it earlier in the lab).

Lab 4. But I still get the error even after adding a line of comment before the `public static void main()`

**Comment by zihaowrez** [comment]
Ok I solved it. Javadoc is not simply a usual comment. This is the format:

```
public class Main {
    /** This is a Javadoc.
    * The second line looks like this */
    public static void main(String[] args) {
    ...
}
```
