### ISSUE TITLE
Test2: Manual typecast?

### ISSUE THREAD

**Issue by davidwang98** [nus-cs2030/2021-s2#68]
# Summary

Unsure if we are supposed to do a manual typecast when using getKey and getValue from the HashMap.

## Description:

Are we supposed to do a manual typecast? I passed the test case but am sure if we are supposed to do it this way.

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

![image](https://user-images.githubusercontent.com/71161461/111023466-28950800-8414-11eb-885d-2a3f8b60857b.png)

**Comment by Keithlimhs** [comment]
Hi there is no need to do manual typecast as your HashMap already stores Strings and Assessments as the key-value pairs. So if you want to retrieve the key in the HashMap it will be returned as a String, and by retrieving the value you will get back an Assessment. Also, your get method can make use of the HashMap's API's get method, which eliminates the need for your if statement

**Comment by davidwang98** [comment]
Thank a lot Keith. Just removed the for and if statements lmao.
