### ISSUE TITLE
ImList implementation unchecked call warning

### ISSUE THREAD

**Issue by KingRyo13** [nus-cs2030/2021-s2#73]
I'm halfway through lecture 7 and decided to code out the ImList class that prof showed to make an Immutable arrayList.
![image](https://user-images.githubusercontent.com/77270665/111071017-34192980-850f-11eb-8b2b-56226f5b0cbb.png)
![image](https://user-images.githubusercontent.com/77270665/111071027-44c99f80-850f-11eb-9c93-64d2deffe82a.png)

Using the add() method works, 
![image](https://user-images.githubusercontent.com/77270665/111070899-c10fb300-850e-11eb-8d16-f6735ecafa15.png)

but using it twice gives this warning, while still ending up working.
![image](https://user-images.githubusercontent.com/77270665/111070938-e00e4500-850e-11eb-8b87-6dc744cdc11b.png)

setting the list to another list also yields a similar error
![image](https://user-images.githubusercontent.com/77270665/111070966-003e0400-850f-11eb-90de-e152c3f8bf22.png)

Does anyone know what it means, what does raw type ImList mean, and how to get rid of the warnings?

Thanks.

**Comment by gableejh** [comment]
Not sure if this will resolve the error, but perhaps you can try to update the method return type to ImList<T> instead of just ImList. Basically adding the <T>

**Comment by KingRyo13** [comment]
> Not sure if this will resolve the error, but perhaps you can try to update the method return type to `ImList<T>` instead of just ImList. Basically adding the `<T>`

Ah yea that was the issue, thanks! :)

**Comment by gableejh** [comment]
> > Not sure if this will resolve the error, but perhaps you can try to update the method return type to `ImList<T>` instead of just ImList. Basically adding the `<T>`
> 
> Ah yea that was the issue, thanks! :)

Most welcome!
