### ISSUE TITLE
BiFunction interface Clarification

### ISSUE THREAD

**Issue by KingRyo13** [nus-cs2030/2021-s2#80]
Hi, I get the other functional interfaces but the BiFunction one is a little confusing for me. Take the reduce() method to sum every integer in a list shown in the lecture:

![image](https://user-images.githubusercontent.com/77270665/111521059-aa2dc280-8793-11eb-9409-b3af91c035c5.png)

Can someone explain

1. What the first < U > represents again, since the next U is the return type
![image](https://user-images.githubusercontent.com/77270665/111521213-de08e800-8793-11eb-9b5c-e7629844aa44.png)

2. What exactly does each letter in each position represent (<U, T, U>)
![image](https://user-images.githubusercontent.com/77270665/111521410-14466780-8794-11eb-997a-f24273a22e4d.png)
I understand for Function<T, R> the T would be the type of the current object, while the R will be the type of the returned object, whether there is or is not a change in type.

3. Am I right to say that if I want to change reduce() to add up every pair in an Integer list and store it in a new list, I can omit having a `U identity` entirely, and instead change the method head to this:
![image](https://user-images.githubusercontent.com/77270665/111522062-d5fd7800-8794-11eb-8d5f-ab15945f1b10.png)
and then have a nested for loop to call mapper.apply and put the pairs in?

Thanks!

**Comment by hwkchia** [comment]
1. `U` is only used within the reduce method, hence it needs to be declared `<U>` at the method level.
2. `reduce` always takes two inputs, and gives one output.  The first `U` and `T` are the inputs, the last `U` is the output.
3. Yes, you can, but that will restrict the use of reduce to only work with a single type.  In this case, there's not even a need to have `R`, and it suffices to be `BiFunction<T,T,T>` (think about it, the first and last type parameters must be the same if we need to do pairwise reduction of stream elements).

**Comment by KingRyo13** [comment]
> 1. `U` is only used within the reduce method, hence it needs to be declared `<U>` at the method level.
> 2. `reduce` always takes two inputs, and gives one output.  The first `U` and `T` are the inputs, the last `U` is the output.
> 3. Yes, you can, but that will restrict the use of reduce to only work with a single type.  In this case, there's not even a need to have `R`, and it suffices to be `BiFunction<T,T,T>` (think about it, the first and last type parameters must be the same if we need to do pairwise reduction of stream elements).

I get it now, thanks for the clarification!
