### ISSUE TITLE
Convert conditioned for loops on indeces to Java stream

### ISSUE THREAD

**Issue by zihaowrez** [nus-cs2030/2021-s2#85]
I wish to convert the following nested for loops to a java stream (for recitation #8).
```
for (int i = 0; i < n; i++) {
    for (int j = i + 1; j < n; j++) {
        Pair.<Point, Point>of(points[i], points[j]);
        ...
    }
}
```
where `points` is an array of `Point` objects.

I have tried
```
IntStream.range(0, points.length)
    .flatMap(i -> IntStream.range(0, points.length)
         .filter(j -> j > i)
         .mapToObj(j -> Pair.<Point, Point>of(points[i], points[j])))
```
where `Pair<T, U>` is a class I have defined.
But I encountered this error 
```
|  Error:
|  incompatible types: bad return type in lambda expression
|      no instance(s) of type variable(s) U exist so that java.util.stream.Stream<U> conforms to java.util.stream.IntStream
|          .flatMap(i -> IntStream.range(0, points.length)
|                        ^--------------------------------...
```

I couldn't figure out how to do this correctly. Can anyone help? Thanks.

**Comment by hwkchia** [comment]
Refer to the `flatMap` method of `IntStream`.  Notice that it takes in a function (`IntFunction`) with the apply method that returns an `IntStream`? Your flatMap actually takes in a function that returns a `Stream<Pair<Point,Point>>`.
