### ISSUE TITLE
Missing a JavaDoc comment. [JavadocMethod]

### ISSUE THREAD

**Issue by ashwinkc-29** [nus-cs2030/2021-s2#87]
# Summary

I am facing this issue when I upload my files onto CodeCrunch in order to pass level 6. Wondering if anyone else is facing this issue and knows how to troubleshoot it. Thanks!

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="632" alt="Screenshot 2021-03-19 at 10 58 53 PM" src="https://user-images.githubusercontent.com/77877020/111800226-b6865c80-8906-11eb-9613-de96c09b8e76.png">

**Comment by JoelToh404** [comment]
you could try to remove public in front of your Main class

**Comment by gableejh** [comment]
You can add comments into your Main,java file, for instance

`/**
   * Description of your method
   * @param key unique key to retrieve assessment grade
   * @return the grade of the assessment
   * \`

**Comment by cf6600** [comment]
There was an earlier post on this #78 (https://github.com/nus-cs2030/2021-s2/issues/78)
For me it worked when i put a comment on top of the public static void main
