### ISSUE TITLE
How to delete file in ubuntu

### ISSUE THREAD

**Issue by ameliacsy** [nus-cs2030/2021-s2#92]
I have a file I want to delete because it is a read-only file but the file doesn't exist in my directory yet I can't create a new class file with the same name, is there any other way I can remove it or create a new class file?

![Screenshot (69)](https://user-images.githubusercontent.com/77654858/111900865-cec5bb00-8a6f-11eb-9d35-2b528d2b7bdc.png)

**Comment by Buwoo** [comment]
I believe you can use rm -rf to remove the file

**Comment by gableejh** [comment]
How about deleting it through File Explorer by going to this directory -> \\wsl$\Ubuntu-18.04\home

**Comment by ydymegan** [comment]
You can either

unlink filename
rm filename

**Comment by mltnsia** [comment]
To remove (or delete) a file in Linux from the command line, use either the rm (remove) or unlink command.

The unlink command allows you to remove only a single file, while with rm you can remove multiple files at once.

**Comment by yowyuxuan** [comment]
you might be in the wrong directory in Ubuntu

**Comment by nicolaineo** [comment]
i would delete mine directly through opening the file itself, that definitely works, renaming as well
