### ISSUE TITLE
What are the uses of Covariant, Contravariant and Invariant?

### ISSUE THREAD

**Issue by ydymegan** [nus-cs2030/2021-s2#95]
Hi! I am revisiting the topics of Lecture 8 and am still confused on the application of covariant, contravariant and invariant while coding. Would appreciate it if anyone could help with the explanation? Thank you so much!

**Comment by mltnsia** [comment]
Hi! Here are the uses based on the Get-Put Principles;

covariant: use extends to get items from a producer*
contravariant: use super to put items into a consumer*
invariant: use neither to get and put

**Comment by gwajoon** [comment]
Hi ydymegan, I had the same question in my head when I was going through the topic as well. I found that this post on StackOverflow helped me understood the concept pretty well. Do take a look and let me know if you got any other questions!
[https://stackoverflow.com/questions/4343202/difference-between-super-t-and-extends-t-in-java](url)

**Comment by keithcharlesc** [comment]
Hey @ydymegan , the variance of types would refer to how the subtype relationship between complex types (like arrays) relates to subtype relationship between components. Suppose there are two types S and T: then let C(S) correspond to some complex type (array of type S).

**Comment by ashleyleerx** [comment]
Hi, using the examples of FastFood and Burger(which is a FastFood)

**1. Covariance would mean to extend to get items from a producer**

Let's create an ArrayList of Burgers

List<Burger> burgers = new ArrayList<Burger>();
burgers.add(new Burger());

List<? extends FastFood> fastfood = burgers // it will work cos Burger is a FastFood
fastfood.add(new Burger()); //Compilation error
fastfood.add(new FastFood()); // Compilation error


We can take out the elements of the List cos the element is definitely going to be a FastFood, hence the basket is only producing the elements.  Thus covariance should be used for retrieving elements 

*2. contravariant: use super to put items into a consumer*r**

**Comment by ydymegan** [comment]
Alright, thanks everyone for the help! :)
